services:
  mongodb:
    image: mongo:7
    container_name: rcthub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rcthub
    volumes:
      - rcthub-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: rcthub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - rcthub-redis-data:/data

volumes:
  rcthub-mongo-data:
  rcthub-redis-data:
