// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"rctHubBackend/internal/matchengine"
	"strconv"
	"time"
)

type Announcement struct {
	ID          string     `json:"id"`
	Pinned      bool       `json:"pinned"`
	Visible     bool       `json:"visible"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	AuthorID    string     `json:"authorID"`
	Author      *User      `json:"author,omitempty"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type AnnouncementPage struct {
	Items      []*Announcement `json:"items"`
	Page       int             `json:"page"`
	PerPage    int             `json:"perPage"`
	Total      int             `json:"total"`
	TotalPages int             `json:"totalPages"`
}

type AuditEntry struct {
	ActionID         string             `json:"actionId"`
	MatchID          string             `json:"matchId"`
	Sequence         string             `json:"sequence"`
	Actor            *MatchCommandActor `json:"actor"`
	CommandType      string             `json:"commandType"`
	PreviousVersion  string             `json:"previousVersion"`
	ResultingVersion string             `json:"resultingVersion"`
	Timestamp        time.Time          `json:"timestamp"`
	Reason           *string            `json:"reason,omitempty"`
}

type BanPoolSlotInput struct {
	Meta       *CommandMeta `json:"meta"`
	PoolSlotID string       `json:"poolSlotId"`
}

type Beatmap struct {
	ID                string    `json:"id"`
	OnlineID          string    `json:"onlineID"`
	BeatmapsetID      string    `json:"beatmapsetID"`
	Title             string    `json:"title"`
	Artist            string    `json:"artist"`
	DifficultyName    string    `json:"difficultyName"`
	Status            string    `json:"status"`
	AuthorID          string    `json:"authorID"`
	Author            *User     `json:"author,omitempty"`
	RulesetID         int       `json:"rulesetID"`
	StarRating        float64   `json:"starRating"`
	Bpm               float64   `json:"bpm"`
	TotalLength       int       `json:"totalLength"`
	DrainRate         float64   `json:"drainRate"`
	CircleSize        float64   `json:"circleSize"`
	ApproachRate      float64   `json:"approachRate"`
	OverallDifficulty float64   `json:"overallDifficulty"`
	CoverURL          string    `json:"coverURL"`
	ModString         string    `json:"modString"`
	ModIndex          int       `json:"modIndex"`
	SelectorID        *string   `json:"selectorID,omitempty"`
	Selector          *User     `json:"selector,omitempty"`
	CreditUserIDs     []string  `json:"creditUserIDs"`
	Credits           []*User   `json:"credits"`
	Skill             *string   `json:"skill,omitempty"`
	Comment           *string   `json:"comment,omitempty"`
	IsOriginal        bool      `json:"isOriginal"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type BeatmapPage struct {
	Items      []*Beatmap `json:"items"`
	Page       int        `json:"page"`
	PerPage    int        `json:"perPage"`
	Total      int        `json:"total"`
	TotalPages int        `json:"totalPages"`
}

type CalibrateTimerInput struct {
	Meta                  *CommandMeta `json:"meta"`
	RemainingMilliseconds int          `json:"remainingMilliseconds"`
	Reason                string       `json:"reason"`
}

type CaptainView struct {
	MyTeam   TeamSide            `json:"myTeam"`
	Analysis *MatchActorAnalysis `json:"analysis"`
}

type CommandMeta struct {
	MatchID         string `json:"matchId"`
	ExpectedVersion string `json:"expectedVersion"`
	CommandID       string `json:"commandId"`
}

type ConfirmBeatmapResultInput struct {
	Meta         *CommandMeta `json:"meta"`
	BoardPieceID string       `json:"boardPieceId"`
	WinningTeam  TeamSide     `json:"winningTeam"`
}

type ConfirmIRCResultInput struct {
	MatchID         string   `json:"matchId"`
	ExpectedVersion string   `json:"expectedVersion"`
	CommandID       string   `json:"commandId"`
	ObservationID   string   `json:"observationId"`
	BoardPieceID    string   `json:"boardPieceId"`
	WinningTeam     TeamSide `json:"winningTeam"`
}

type ConfirmTbResultInput struct {
	Meta        *CommandMeta `json:"meta"`
	WinningTeam TeamSide     `json:"winningTeam"`
}

type FormalBoard struct {
	Cells []*FormalBoardCell `json:"cells"`
}

type FormalBoardCell struct {
	Cell  string            `json:"cell"`
	Row   int               `json:"row"`
	Col   int               `json:"col"`
	Zone  FormalBoardZone   `json:"zone"`
	Piece *FormalBoardPiece `json:"piece,omitempty"`
}

type FormalBoardPiece struct {
	ID               string            `json:"id"`
	SourcePoolSlotID string            `json:"sourcePoolSlotID"`
	Mod              PieceMod          `json:"mod"`
	ForceMod         *ForceMod         `json:"forceMod,omitempty"`
	SelectedBy       TeamSide          `json:"selectedBy"`
	Owner            *TeamSide         `json:"owner,omitempty"`
	Outcome          BoardPieceOutcome `json:"outcome"`
}

type FormalMatchResult struct {
	Winner              TeamSide          `json:"winner"`
	Reason              MatchResultReason `json:"reason"`
	SurrenderingTeam    *TeamSide         `json:"surrenderingTeam,omitempty"`
	ConfirmingPlayerIDs []string          `json:"confirmingPlayerIDs"`
	WonCounts           *TeamCounts       `json:"wonCounts"`
}

type FormalPoolSlot struct {
	ID    string        `json:"id"`
	Mod   PieceMod      `json:"mod"`
	State PoolSlotState `json:"state"`
}

type FormalRoster struct {
	LeaderID  string   `json:"leaderID"`
	PlayerIDs []string `json:"playerIDs"`
}

type FormalRosters struct {
	Red  *FormalRoster `json:"red"`
	Blue *FormalRoster `json:"blue"`
}

type FormalTimer struct {
	StartedAt                    *time.Time `json:"startedAt,omitempty"`
	DurationMilliseconds         int        `json:"durationMilliseconds"`
	Paused                       bool       `json:"paused"`
	RemainingAtPauseMilliseconds *int       `json:"remainingAtPauseMilliseconds,omitempty"`
}

type IRCConnectionStatus struct {
	Configured bool    `json:"configured"`
	Connected  bool    `json:"connected"`
	Degraded   bool    `json:"degraded"`
	LastError  *string `json:"lastError,omitempty"`
}

type IRCJob struct {
	ID             string       `json:"id"`
	MatchID        string       `json:"matchID"`
	Channel        string       `json:"channel"`
	Kind           string       `json:"kind"`
	Payload        string       `json:"payload"`
	Status         IRCJobStatus `json:"status"`
	Attempts       int          `json:"attempts"`
	AutomaticRetry bool         `json:"automaticRetry"`
	NextTryAt      *time.Time   `json:"nextTryAt,omitempty"`
	SentAt         *time.Time   `json:"sentAt,omitempty"`
	AckDeadline    *time.Time   `json:"ackDeadline,omitempty"`
	AcknowledgedAt *time.Time   `json:"acknowledgedAt,omitempty"`
	LastError      *string      `json:"lastError,omitempty"`
}

type IRCObservation struct {
	ID              string              `json:"id"`
	Channel         string              `json:"channel"`
	Sender          string              `json:"sender"`
	Command         string              `json:"command"`
	Raw             string              `json:"raw"`
	ObservedAt      time.Time           `json:"observedAt"`
	ReviewStatus    IRCReviewStatus     `json:"reviewStatus"`
	ReviewReason    *string             `json:"reviewReason,omitempty"`
	SuggestedResult *IRCSuggestedResult `json:"suggestedResult,omitempty"`
}

type IRCSuggestedResult struct {
	WinningTeam  TeamSide `json:"winningTeam"`
	BoardPieceID string   `json:"boardPieceID"`
}

type LegalPlacement struct {
	PoolSlotID string    `json:"poolSlotID"`
	Cell       string    `json:"cell"`
	ForceMod   *ForceMod `json:"forceMod,omitempty"`
}

type Mappool struct {
	Slots []*PoolSlotGroup `json:"slots"`
}

type Match struct {
	ID             string                   `json:"id"`
	Code           string                   `json:"code"`
	Name           string                   `json:"name"`
	RoomType       RoomType                 `json:"roomType"`
	RoomID         string                   `json:"roomID"`
	Room           *Room                    `json:"room,omitempty"`
	Pool           []*MatchPoolSlotMetadata `json:"pool"`
	StrategistView *StrategistView          `json:"strategistView,omitempty"`
	CaptainView    *CaptainView             `json:"captainView,omitempty"`
	SpectatorView  *SpectatorView           `json:"spectatorView"`
	OverlayView    *OverlayView             `json:"overlayView"`
	RefereeView    *RefereeView             `json:"refereeView,omitempty"`
	CreatedAt      time.Time                `json:"createdAt"`
	Snapshot       *MatchSnapshot           `json:"snapshot"`
	// Authoritative state captured with this GraphQL object; never exposed directly.
	State matchengine.State `json:"-"`
}

type MatchActorAnalysis struct {
	AllowedActions     []MatchAction     `json:"allowedActions"`
	BanPoolSlotIDs     []string          `json:"banPoolSlotIDs"`
	LegalPlacements    []*LegalPlacement `json:"legalPlacements"`
	ShiroCells         []string          `json:"shiroCells"`
	RobberyPlans       []*RobberyPlan    `json:"robberyPlans"`
	PendingTBRequestID *string           `json:"pendingTBRequestID,omitempty"`
	CanAcceptTBRequest bool              `json:"canAcceptTBRequest"`
	CanRejectTBRequest bool              `json:"canRejectTBRequest"`
	TbRequestTeams     []TeamSide        `json:"tbRequestTeams"`
	TbResponseTeams    []TeamSide        `json:"tbResponseTeams"`
}

type MatchAutomationIssue struct {
	EventID    string         `json:"eventID"`
	Sequence   string         `json:"sequence"`
	EventType  MatchEventType `json:"eventType"`
	Attempts   int            `json:"attempts"`
	LastError  string         `json:"lastError"`
	OccurredAt time.Time      `json:"occurredAt"`
}

type MatchCommandActor struct {
	OsuID           string               `json:"osuID"`
	Capability      MatchActorCapability `json:"capability"`
	Team            *TeamSide            `json:"team,omitempty"`
	AdminOverride   bool                 `json:"adminOverride"`
	RefereeOverride bool                 `json:"refereeOverride"`
}

type MatchCommandEvent struct {
	EventID          string             `json:"eventId"`
	SchemaVersion    int                `json:"schemaVersion"`
	AggregateID      string             `json:"aggregateId"`
	AggregateType    string             `json:"aggregateType"`
	Sequence         string             `json:"sequence"`
	ResultingVersion string             `json:"resultingVersion"`
	Type             MatchEventType     `json:"type"`
	OccurredAt       time.Time          `json:"occurredAt"`
	Actor            *MatchCommandActor `json:"actor"`
	Fact             *MatchEventFact    `json:"fact"`
}

type MatchCommandResult struct {
	Success          bool                     `json:"success"`
	CommandID        string                   `json:"commandId"`
	Disposition      *MatchCommandDisposition `json:"disposition,omitempty"`
	PreviousVersion  *string                  `json:"previousVersion,omitempty"`
	ResultingVersion *string                  `json:"resultingVersion,omitempty"`
	CurrentVersion   *string                  `json:"currentVersion,omitempty"`
	Snapshot         *MatchSnapshot           `json:"snapshot,omitempty"`
	Events           []*MatchCommandEvent     `json:"events"`
	Error            *MatchError              `json:"error,omitempty"`
}

type MatchError struct {
	Code           MatchErrorCode `json:"code"`
	Message        string         `json:"message"`
	CurrentVersion *string        `json:"currentVersion,omitempty"`
}

type MatchEventFact struct {
	Team                 *TeamSide `json:"team,omitempty"`
	PoolSlotID           *string   `json:"poolSlotID,omitempty"`
	BoardPieceID         *string   `json:"boardPieceID,omitempty"`
	BoardPieceIDs        []string  `json:"boardPieceIDs"`
	Cell                 *string   `json:"cell,omitempty"`
	DurationMilliseconds *int      `json:"durationMilliseconds,omitempty"`
	Reason               *string   `json:"reason,omitempty"`
	RequestID            *string   `json:"requestID,omitempty"`
	TbBasis              *TBBasis  `json:"tbBasis,omitempty"`
	PlayerIDs            []string  `json:"playerIDs"`
}

type MatchPage struct {
	Items      []*Match `json:"items"`
	Page       int      `json:"page"`
	PerPage    int      `json:"perPage"`
	Total      int      `json:"total"`
	TotalPages int      `json:"totalPages"`
}

type MatchPoolSlotMetadata struct {
	PoolSlotID          string                `json:"poolSlotID"`
	BeatmapID           *string               `json:"beatmapID,omitempty"`
	Beatmap             *Beatmap              `json:"beatmap,omitempty"`
	MetadataStatus      BeatmapMetadataStatus `json:"metadataStatus"`
	MetadataAttempts    int                   `json:"metadataAttempts"`
	MetadataNextRetryAt *time.Time            `json:"metadataNextRetryAt,omitempty"`
	MetadataLastError   *string               `json:"metadataLastError,omitempty"`
}

type MatchSnapshot struct {
	Version          string             `json:"version"`
	Lifecycle        MatchLifecycle     `json:"lifecycle"`
	Phase            FormalMatchPhase   `json:"phase"`
	FirstBan         TeamSide           `json:"firstBan"`
	FirstPick        TeamSide           `json:"firstPick"`
	Turn             int                `json:"turn"`
	ActiveTeam       *TeamSide          `json:"activeTeam,omitempty"`
	PoolSlots        []*FormalPoolSlot  `json:"poolSlots"`
	Board            *FormalBoard       `json:"board"`
	WonCounts        *TeamCounts        `json:"wonCounts"`
	Timer            *FormalTimer       `json:"timer"`
	RobberyUsed      *TeamFlags         `json:"robberyUsed"`
	TeamPauseUsed    *TeamFlags         `json:"teamPauseUsed"`
	Rosters          *FormalRosters     `json:"rosters"`
	PendingPieceID   *string            `json:"pendingPieceID,omitempty"`
	PendingTBRequest *PendingTBRequest  `json:"pendingTBRequest,omitempty"`
	TbEntry          *TBEntry           `json:"tbEntry,omitempty"`
	Winner           *TeamSide          `json:"winner,omitempty"`
	Result           *FormalMatchResult `json:"result,omitempty"`
	Stalemate        *StalemateEvidence `json:"stalemate,omitempty"`
}

type Mutation struct {
}

type OverlayView struct {
	Board      *FormalBoard     `json:"board"`
	WonCounts  *TeamCounts      `json:"wonCounts"`
	Timer      *FormalTimer     `json:"timer"`
	Lifecycle  MatchLifecycle   `json:"lifecycle"`
	Phase      FormalMatchPhase `json:"phase"`
	ActiveTeam *TeamSide        `json:"activeTeam,omitempty"`
}

type PendingTBRequest struct {
	ID          string   `json:"id"`
	RequestedBy TeamSide `json:"requestedBy"`
	Basis       TBBasis  `json:"basis"`
}

type PlacePieceInput struct {
	Meta       *CommandMeta   `json:"meta"`
	PoolSlotID string         `json:"poolSlotId"`
	Position   *PositionInput `json:"position"`
}

type PlaceShiroInput struct {
	Meta     *CommandMeta   `json:"meta"`
	Position *PositionInput `json:"position"`
}

type PoolSlot struct {
	Mod       PieceMod   `json:"mod"`
	Index     int        `json:"index"`
	BeatmapID *string    `json:"beatmapID,omitempty"`
	Beatmap   *Beatmap   `json:"beatmap,omitempty"`
	State     PieceState `json:"state"`
	TeamID    *string    `json:"teamID,omitempty"`
	ForceMod  *string    `json:"forceMod,omitempty"`
	Position  *Position  `json:"position,omitempty"`
}

type PoolSlotGroup struct {
	Mod    PieceMod    `json:"mod"`
	Pieces []*PoolSlot `json:"pieces"`
}

type Position struct {
	Row int `json:"row"`
	Col int `json:"col"`
}

type PositionInput struct {
	Row int `json:"row"`
	Col int `json:"col"`
}

type Query struct {
}

type ReasonCommandInput struct {
	Meta   *CommandMeta `json:"meta"`
	Reason string       `json:"reason"`
}

type RecordSurrenderInput struct {
	Meta                *CommandMeta `json:"meta"`
	SurrenderingTeam    TeamSide     `json:"surrenderingTeam"`
	ConfirmingPlayerIds []string     `json:"confirmingPlayerIds"`
	Reason              string       `json:"reason"`
}

type RefereeBanPoolSlotInput struct {
	Meta       *CommandMeta `json:"meta"`
	ActingTeam TeamSide     `json:"actingTeam"`
	PoolSlotID string       `json:"poolSlotId"`
	Reason     string       `json:"reason"`
}

type RefereePlacePieceInput struct {
	Meta       *CommandMeta   `json:"meta"`
	ActingTeam TeamSide       `json:"actingTeam"`
	PoolSlotID string         `json:"poolSlotId"`
	Position   *PositionInput `json:"position"`
	Reason     string         `json:"reason"`
}

type RefereePlaceShiroInput struct {
	Meta       *CommandMeta   `json:"meta"`
	ActingTeam TeamSide       `json:"actingTeam"`
	Position   *PositionInput `json:"position"`
	Reason     string         `json:"reason"`
}

type RefereeRequestTbInput struct {
	Meta       *CommandMeta `json:"meta"`
	ActingTeam TeamSide     `json:"actingTeam"`
	RequestID  string       `json:"requestId"`
	Reason     string       `json:"reason"`
}

type RefereeRespondTbRequestInput struct {
	Meta       *CommandMeta `json:"meta"`
	ActingTeam TeamSide     `json:"actingTeam"`
	RequestID  string       `json:"requestId"`
	Accept     bool         `json:"accept"`
	Reason     string       `json:"reason"`
}

type RefereeRobPieceInput struct {
	Meta          *CommandMeta `json:"meta"`
	ActingTeam    TeamSide     `json:"actingTeam"`
	TargetPieceID string       `json:"targetPieceId"`
	SacrificeSets [][]string   `json:"sacrificeSets"`
	Reason        string       `json:"reason"`
}

type RefereeView struct {
	MatchID          string                  `json:"matchID"`
	Snapshot         *MatchSnapshot          `json:"snapshot"`
	Analysis         *MatchActorAnalysis     `json:"analysis"`
	SuspensionReason *string                 `json:"suspensionReason,omitempty"`
	AbortReason      *string                 `json:"abortReason,omitempty"`
	AuditLog         []*AuditEntry           `json:"auditLog"`
	AutomationIssues []*MatchAutomationIssue `json:"automationIssues"`
}

type RequestTbInput struct {
	Meta      *CommandMeta `json:"meta"`
	RequestID string       `json:"requestId"`
}

type RespondTbRequestInput struct {
	Meta      *CommandMeta `json:"meta"`
	RequestID string       `json:"requestId"`
	Accept    bool         `json:"accept"`
}

type RetryBeatmapMetadataInput struct {
	MatchID   string `json:"matchID"`
	BeatmapID string `json:"beatmapID"`
}

type RetryIRCJobInput struct {
	MatchID string `json:"matchID"`
	JobID   string `json:"jobID"`
}

type RetryMatchAutomationInput struct {
	MatchID string `json:"matchID"`
	EventID string `json:"eventID"`
}

type RobPieceInput struct {
	Meta          *CommandMeta `json:"meta"`
	TargetPieceID string       `json:"targetPieceId"`
	SacrificeSets [][]string   `json:"sacrificeSets"`
}

type RobberyPlan struct {
	TargetPieceID string     `json:"targetPieceID"`
	SacrificeSets [][]string `json:"sacrificeSets"`
}

type Room struct {
	ID        string        `json:"id"`
	Code      string        `json:"code"`
	Name      string        `json:"name"`
	Type      RoomType      `json:"type"`
	OwnerID   string        `json:"ownerID"`
	Owner     *User         `json:"owner,omitempty"`
	Settings  *RoomSettings `json:"settings"`
	MatchID   *string       `json:"matchID,omitempty"`
	Match     *Match        `json:"match,omitempty"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

type RoomPage struct {
	Items      []*Room `json:"items"`
	Page       int     `json:"page"`
	PerPage    int     `json:"perPage"`
	Total      int     `json:"total"`
	TotalPages int     `json:"totalPages"`
}

type RoomSettings struct {
	RedStrategistUserID  *string   `json:"redStrategistUserID,omitempty"`
	RedStrategist        *User     `json:"redStrategist,omitempty"`
	BlueStrategistUserID *string   `json:"blueStrategistUserID,omitempty"`
	BlueStrategist       *User     `json:"blueStrategist,omitempty"`
	StreamerUserID       *string   `json:"streamerUserID,omitempty"`
	Streamer             *User     `json:"streamer,omitempty"`
	Mappool              *Mappool  `json:"mappool"`
	FirstPick            *TeamSide `json:"firstPick,omitempty"`
	FirstBan             *TeamSide `json:"firstBan,omitempty"`
	RedPlayers           []string  `json:"redPlayers"`
	BluePlayers          []string  `json:"bluePlayers"`
	RedLeader            *string   `json:"redLeader,omitempty"`
	BlueLeader           *string   `json:"blueLeader,omitempty"`
	MpLink               *string   `json:"mpLink,omitempty"`
	StreamLink           *string   `json:"streamLink,omitempty"`
}

type SpectatorView struct {
	Board        *FormalBoard     `json:"board"`
	WonCounts    *TeamCounts      `json:"wonCounts"`
	CurrentPhase FormalMatchPhase `json:"currentPhase"`
	ActiveTeam   *TeamSide        `json:"activeTeam,omitempty"`
	TurnNumber   int              `json:"turnNumber"`
	Lifecycle    MatchLifecycle   `json:"lifecycle"`
}

type StalemateEvidence struct {
	WonCounts *TeamCounts `json:"wonCounts"`
}

type StrategistView struct {
	IsMyTurn bool                `json:"isMyTurn"`
	MyTeam   TeamSide            `json:"myTeam"`
	Analysis *MatchActorAnalysis `json:"analysis"`
}

type TBEntry struct {
	Basis       TBBasis   `json:"basis"`
	RequestID   *string   `json:"requestID,omitempty"`
	RequestedBy *TeamSide `json:"requestedBy,omitempty"`
}

type TeamCounts struct {
	Red  int `json:"red"`
	Blue int `json:"blue"`
}

type TeamFlags struct {
	Red  bool `json:"red"`
	Blue bool `json:"blue"`
}

type User struct {
	ID           string       `json:"id"`
	OnlineID     string       `json:"onlineID"`
	Username     string       `json:"username"`
	AvatarURL    string       `json:"avatarURL"`
	CountryCode  string       `json:"countryCode"`
	GlobalRank   *int         `json:"globalRank,omitempty"`
	Pp           *float64     `json:"pp,omitempty"`
	VerifyStatus VerifyStatus `json:"verifyStatus"`
	IsBanned     bool         `json:"isBanned"`
	Roles        []UserRole   `json:"roles"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    time.Time    `json:"updatedAt"`
}

type UserPage struct {
	Items      []*User `json:"items"`
	Page       int     `json:"page"`
	PerPage    int     `json:"perPage"`
	Total      int     `json:"total"`
	TotalPages int     `json:"totalPages"`
}

type BeatmapMetadataStatus string

const (
	BeatmapMetadataStatusNotConfigured BeatmapMetadataStatus = "NOT_CONFIGURED"
	BeatmapMetadataStatusReady         BeatmapMetadataStatus = "READY"
	BeatmapMetadataStatusPending       BeatmapMetadataStatus = "PENDING"
	BeatmapMetadataStatusFailed        BeatmapMetadataStatus = "FAILED"
)

var AllBeatmapMetadataStatus = []BeatmapMetadataStatus{
	BeatmapMetadataStatusNotConfigured,
	BeatmapMetadataStatusReady,
	BeatmapMetadataStatusPending,
	BeatmapMetadataStatusFailed,
}

func (e BeatmapMetadataStatus) IsValid() bool {
	switch e {
	case BeatmapMetadataStatusNotConfigured, BeatmapMetadataStatusReady, BeatmapMetadataStatusPending, BeatmapMetadataStatusFailed:
		return true
	}
	return false
}

func (e BeatmapMetadataStatus) String() string {
	return string(e)
}

func (e *BeatmapMetadataStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BeatmapMetadataStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BeatmapMetadataStatus", str)
	}
	return nil
}

func (e BeatmapMetadataStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BeatmapMetadataStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BeatmapMetadataStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BoardPieceOutcome string

const (
	BoardPieceOutcomeWaitingResult BoardPieceOutcome = "WAITING_RESULT"
	BoardPieceOutcomeWon           BoardPieceOutcome = "WON"
	BoardPieceOutcomeWhite         BoardPieceOutcome = "WHITE"
	BoardPieceOutcomeDead          BoardPieceOutcome = "DEAD"
)

var AllBoardPieceOutcome = []BoardPieceOutcome{
	BoardPieceOutcomeWaitingResult,
	BoardPieceOutcomeWon,
	BoardPieceOutcomeWhite,
	BoardPieceOutcomeDead,
}

func (e BoardPieceOutcome) IsValid() bool {
	switch e {
	case BoardPieceOutcomeWaitingResult, BoardPieceOutcomeWon, BoardPieceOutcomeWhite, BoardPieceOutcomeDead:
		return true
	}
	return false
}

func (e BoardPieceOutcome) String() string {
	return string(e)
}

func (e *BoardPieceOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BoardPieceOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BoardPieceOutcome", str)
	}
	return nil
}

func (e BoardPieceOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BoardPieceOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BoardPieceOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ForceMod string

const (
	ForceModNm ForceMod = "NM"
	ForceModHd ForceMod = "HD"
	ForceModHr ForceMod = "HR"
)

var AllForceMod = []ForceMod{
	ForceModNm,
	ForceModHd,
	ForceModHr,
}

func (e ForceMod) IsValid() bool {
	switch e {
	case ForceModNm, ForceModHd, ForceModHr:
		return true
	}
	return false
}

func (e ForceMod) String() string {
	return string(e)
}

func (e *ForceMod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ForceMod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ForceMod", str)
	}
	return nil
}

func (e ForceMod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ForceMod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ForceMod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FormalBoardZone string

const (
	FormalBoardZoneDt FormalBoardZone = "DT"
	FormalBoardZoneHd FormalBoardZone = "HD"
	FormalBoardZoneHr FormalBoardZone = "HR"
)

var AllFormalBoardZone = []FormalBoardZone{
	FormalBoardZoneDt,
	FormalBoardZoneHd,
	FormalBoardZoneHr,
}

func (e FormalBoardZone) IsValid() bool {
	switch e {
	case FormalBoardZoneDt, FormalBoardZoneHd, FormalBoardZoneHr:
		return true
	}
	return false
}

func (e FormalBoardZone) String() string {
	return string(e)
}

func (e *FormalBoardZone) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FormalBoardZone(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FormalBoardZone", str)
	}
	return nil
}

func (e FormalBoardZone) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FormalBoardZone) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FormalBoardZone) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FormalMatchPhase string

const (
	FormalMatchPhaseNone             FormalMatchPhase = "NONE"
	FormalMatchPhaseBan              FormalMatchPhase = "BAN"
	FormalMatchPhasePick             FormalMatchPhase = "PICK"
	FormalMatchPhaseWaitingForResult FormalMatchPhase = "WAITING_FOR_RESULT"
	FormalMatchPhaseTbPreparation    FormalMatchPhase = "TB_PREPARATION"
	FormalMatchPhaseTbPlaying        FormalMatchPhase = "TB_PLAYING"
)

var AllFormalMatchPhase = []FormalMatchPhase{
	FormalMatchPhaseNone,
	FormalMatchPhaseBan,
	FormalMatchPhasePick,
	FormalMatchPhaseWaitingForResult,
	FormalMatchPhaseTbPreparation,
	FormalMatchPhaseTbPlaying,
}

func (e FormalMatchPhase) IsValid() bool {
	switch e {
	case FormalMatchPhaseNone, FormalMatchPhaseBan, FormalMatchPhasePick, FormalMatchPhaseWaitingForResult, FormalMatchPhaseTbPreparation, FormalMatchPhaseTbPlaying:
		return true
	}
	return false
}

func (e FormalMatchPhase) String() string {
	return string(e)
}

func (e *FormalMatchPhase) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FormalMatchPhase(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FormalMatchPhase", str)
	}
	return nil
}

func (e FormalMatchPhase) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FormalMatchPhase) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FormalMatchPhase) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IRCJobStatus string

const (
	IRCJobStatusPending      IRCJobStatus = "PENDING"
	IRCJobStatusSending      IRCJobStatus = "SENDING"
	IRCJobStatusSent         IRCJobStatus = "SENT"
	IRCJobStatusAcknowledged IRCJobStatus = "ACKNOWLEDGED"
	IRCJobStatusFailed       IRCJobStatus = "FAILED"
	IRCJobStatusCancelled    IRCJobStatus = "CANCELLED"
)

var AllIRCJobStatus = []IRCJobStatus{
	IRCJobStatusPending,
	IRCJobStatusSending,
	IRCJobStatusSent,
	IRCJobStatusAcknowledged,
	IRCJobStatusFailed,
	IRCJobStatusCancelled,
}

func (e IRCJobStatus) IsValid() bool {
	switch e {
	case IRCJobStatusPending, IRCJobStatusSending, IRCJobStatusSent, IRCJobStatusAcknowledged, IRCJobStatusFailed, IRCJobStatusCancelled:
		return true
	}
	return false
}

func (e IRCJobStatus) String() string {
	return string(e)
}

func (e *IRCJobStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IRCJobStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IRCJobStatus", str)
	}
	return nil
}

func (e IRCJobStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IRCJobStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IRCJobStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IRCReviewStatus string

const (
	IRCReviewStatusPending    IRCReviewStatus = "PENDING"
	IRCReviewStatusConfirming IRCReviewStatus = "CONFIRMING"
	IRCReviewStatusConfirmed  IRCReviewStatus = "CONFIRMED"
	IRCReviewStatusRejected   IRCReviewStatus = "REJECTED"
)

var AllIRCReviewStatus = []IRCReviewStatus{
	IRCReviewStatusPending,
	IRCReviewStatusConfirming,
	IRCReviewStatusConfirmed,
	IRCReviewStatusRejected,
}

func (e IRCReviewStatus) IsValid() bool {
	switch e {
	case IRCReviewStatusPending, IRCReviewStatusConfirming, IRCReviewStatusConfirmed, IRCReviewStatusRejected:
		return true
	}
	return false
}

func (e IRCReviewStatus) String() string {
	return string(e)
}

func (e *IRCReviewStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IRCReviewStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IRCReviewStatus", str)
	}
	return nil
}

func (e IRCReviewStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IRCReviewStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IRCReviewStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchAction string

const (
	MatchActionStartMatch           MatchAction = "START_MATCH"
	MatchActionBanPoolSlot          MatchAction = "BAN_POOL_SLOT"
	MatchActionPlacePiece           MatchAction = "PLACE_PIECE"
	MatchActionPlaceShiro           MatchAction = "PLACE_SHIRO"
	MatchActionRobPiece             MatchAction = "ROB_PIECE"
	MatchActionConfirmBeatmapResult MatchAction = "CONFIRM_BEATMAP_RESULT"
	MatchActionGrantAdditionalTime  MatchAction = "GRANT_ADDITIONAL_TIME"
	MatchActionCalibrateTimer       MatchAction = "CALIBRATE_TIMER"
	MatchActionPauseTimer           MatchAction = "PAUSE_TIMER"
	MatchActionResumeTimer          MatchAction = "RESUME_TIMER"
	MatchActionSuspendMatch         MatchAction = "SUSPEND_MATCH"
	MatchActionResumeMatch          MatchAction = "RESUME_MATCH"
	MatchActionSkipCurrentAction    MatchAction = "SKIP_CURRENT_ACTION"
	MatchActionAbortMatch           MatchAction = "ABORT_MATCH"
	MatchActionRequestTb            MatchAction = "REQUEST_TB"
	MatchActionRespondTbRequest     MatchAction = "RESPOND_TB_REQUEST"
	MatchActionStartTb              MatchAction = "START_TB"
	MatchActionConfirmTbResult      MatchAction = "CONFIRM_TB_RESULT"
	MatchActionRecordSurrender      MatchAction = "RECORD_SURRENDER"
)

var AllMatchAction = []MatchAction{
	MatchActionStartMatch,
	MatchActionBanPoolSlot,
	MatchActionPlacePiece,
	MatchActionPlaceShiro,
	MatchActionRobPiece,
	MatchActionConfirmBeatmapResult,
	MatchActionGrantAdditionalTime,
	MatchActionCalibrateTimer,
	MatchActionPauseTimer,
	MatchActionResumeTimer,
	MatchActionSuspendMatch,
	MatchActionResumeMatch,
	MatchActionSkipCurrentAction,
	MatchActionAbortMatch,
	MatchActionRequestTb,
	MatchActionRespondTbRequest,
	MatchActionStartTb,
	MatchActionConfirmTbResult,
	MatchActionRecordSurrender,
}

func (e MatchAction) IsValid() bool {
	switch e {
	case MatchActionStartMatch, MatchActionBanPoolSlot, MatchActionPlacePiece, MatchActionPlaceShiro, MatchActionRobPiece, MatchActionConfirmBeatmapResult, MatchActionGrantAdditionalTime, MatchActionCalibrateTimer, MatchActionPauseTimer, MatchActionResumeTimer, MatchActionSuspendMatch, MatchActionResumeMatch, MatchActionSkipCurrentAction, MatchActionAbortMatch, MatchActionRequestTb, MatchActionRespondTbRequest, MatchActionStartTb, MatchActionConfirmTbResult, MatchActionRecordSurrender:
		return true
	}
	return false
}

func (e MatchAction) String() string {
	return string(e)
}

func (e *MatchAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchAction", str)
	}
	return nil
}

func (e MatchAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchActorCapability string

const (
	MatchActorCapabilityStrategist MatchActorCapability = "STRATEGIST"
	MatchActorCapabilityCaptain    MatchActorCapability = "CAPTAIN"
	MatchActorCapabilityReferee    MatchActorCapability = "REFEREE"
)

var AllMatchActorCapability = []MatchActorCapability{
	MatchActorCapabilityStrategist,
	MatchActorCapabilityCaptain,
	MatchActorCapabilityReferee,
}

func (e MatchActorCapability) IsValid() bool {
	switch e {
	case MatchActorCapabilityStrategist, MatchActorCapabilityCaptain, MatchActorCapabilityReferee:
		return true
	}
	return false
}

func (e MatchActorCapability) String() string {
	return string(e)
}

func (e *MatchActorCapability) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchActorCapability(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchActorCapability", str)
	}
	return nil
}

func (e MatchActorCapability) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchActorCapability) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchActorCapability) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchCommandDisposition string

const (
	MatchCommandDispositionApplied  MatchCommandDisposition = "APPLIED"
	MatchCommandDispositionReplayed MatchCommandDisposition = "REPLAYED"
)

var AllMatchCommandDisposition = []MatchCommandDisposition{
	MatchCommandDispositionApplied,
	MatchCommandDispositionReplayed,
}

func (e MatchCommandDisposition) IsValid() bool {
	switch e {
	case MatchCommandDispositionApplied, MatchCommandDispositionReplayed:
		return true
	}
	return false
}

func (e MatchCommandDisposition) String() string {
	return string(e)
}

func (e *MatchCommandDisposition) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchCommandDisposition(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchCommandDisposition", str)
	}
	return nil
}

func (e MatchCommandDisposition) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchCommandDisposition) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchCommandDisposition) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchErrorCode string

const (
	MatchErrorCodeInvalidRequest            MatchErrorCode = "INVALID_REQUEST"
	MatchErrorCodeAuthRequired              MatchErrorCode = "AUTH_REQUIRED"
	MatchErrorCodeUserNotVerified           MatchErrorCode = "USER_NOT_VERIFIED"
	MatchErrorCodeUserBanned                MatchErrorCode = "USER_BANNED"
	MatchErrorCodeGlobalRoleRequired        MatchErrorCode = "GLOBAL_ROLE_REQUIRED"
	MatchErrorCodeRoomRoleRequired          MatchErrorCode = "ROOM_ROLE_REQUIRED"
	MatchErrorCodeActionNotAllowed          MatchErrorCode = "ACTION_NOT_ALLOWED"
	MatchErrorCodeResourceNotFound          MatchErrorCode = "RESOURCE_NOT_FOUND"
	MatchErrorCodeMatchVersionConflict      MatchErrorCode = "MATCH_VERSION_CONFLICT"
	MatchErrorCodeDuplicateCommandMismatch  MatchErrorCode = "DUPLICATE_COMMAND_MISMATCH"
	MatchErrorCodeInternalError             MatchErrorCode = "INTERNAL_ERROR"
	MatchErrorCodeMatchLifecycleConflict    MatchErrorCode = "MATCH_LIFECYCLE_CONFLICT"
	MatchErrorCodeMatchPhaseConflict        MatchErrorCode = "MATCH_PHASE_CONFLICT"
	MatchErrorCodeNotActiveTeam             MatchErrorCode = "NOT_ACTIVE_TEAM"
	MatchErrorCodeInvalidPoolSlot           MatchErrorCode = "INVALID_POOL_SLOT"
	MatchErrorCodePoolSlotUnavailable       MatchErrorCode = "POOL_SLOT_UNAVAILABLE"
	MatchErrorCodeInvalidBoardCell          MatchErrorCode = "INVALID_BOARD_CELL"
	MatchErrorCodeInvalidModZone            MatchErrorCode = "INVALID_MOD_ZONE"
	MatchErrorCodeResultNotPending          MatchErrorCode = "RESULT_NOT_PENDING"
	MatchErrorCodeTimerExpired              MatchErrorCode = "TIMER_EXPIRED"
	MatchErrorCodeTimerPaused               MatchErrorCode = "TIMER_PAUSED"
	MatchErrorCodeTeamPauseAlreadyUsed      MatchErrorCode = "TEAM_PAUSE_ALREADY_USED"
	MatchErrorCodeRobberyNotAvailable       MatchErrorCode = "ROBBERY_NOT_AVAILABLE"
	MatchErrorCodeRobberyRequirementsNotMet MatchErrorCode = "ROBBERY_REQUIREMENTS_NOT_MET"
	MatchErrorCodeAlignmentOverlap          MatchErrorCode = "ALIGNMENT_OVERLAP"
	MatchErrorCodeTbNotAvailable            MatchErrorCode = "TB_NOT_AVAILABLE"
	MatchErrorCodeSurrenderEvidenceInvalid  MatchErrorCode = "SURRENDER_EVIDENCE_INVALID"
)

var AllMatchErrorCode = []MatchErrorCode{
	MatchErrorCodeInvalidRequest,
	MatchErrorCodeAuthRequired,
	MatchErrorCodeUserNotVerified,
	MatchErrorCodeUserBanned,
	MatchErrorCodeGlobalRoleRequired,
	MatchErrorCodeRoomRoleRequired,
	MatchErrorCodeActionNotAllowed,
	MatchErrorCodeResourceNotFound,
	MatchErrorCodeMatchVersionConflict,
	MatchErrorCodeDuplicateCommandMismatch,
	MatchErrorCodeInternalError,
	MatchErrorCodeMatchLifecycleConflict,
	MatchErrorCodeMatchPhaseConflict,
	MatchErrorCodeNotActiveTeam,
	MatchErrorCodeInvalidPoolSlot,
	MatchErrorCodePoolSlotUnavailable,
	MatchErrorCodeInvalidBoardCell,
	MatchErrorCodeInvalidModZone,
	MatchErrorCodeResultNotPending,
	MatchErrorCodeTimerExpired,
	MatchErrorCodeTimerPaused,
	MatchErrorCodeTeamPauseAlreadyUsed,
	MatchErrorCodeRobberyNotAvailable,
	MatchErrorCodeRobberyRequirementsNotMet,
	MatchErrorCodeAlignmentOverlap,
	MatchErrorCodeTbNotAvailable,
	MatchErrorCodeSurrenderEvidenceInvalid,
}

func (e MatchErrorCode) IsValid() bool {
	switch e {
	case MatchErrorCodeInvalidRequest, MatchErrorCodeAuthRequired, MatchErrorCodeUserNotVerified, MatchErrorCodeUserBanned, MatchErrorCodeGlobalRoleRequired, MatchErrorCodeRoomRoleRequired, MatchErrorCodeActionNotAllowed, MatchErrorCodeResourceNotFound, MatchErrorCodeMatchVersionConflict, MatchErrorCodeDuplicateCommandMismatch, MatchErrorCodeInternalError, MatchErrorCodeMatchLifecycleConflict, MatchErrorCodeMatchPhaseConflict, MatchErrorCodeNotActiveTeam, MatchErrorCodeInvalidPoolSlot, MatchErrorCodePoolSlotUnavailable, MatchErrorCodeInvalidBoardCell, MatchErrorCodeInvalidModZone, MatchErrorCodeResultNotPending, MatchErrorCodeTimerExpired, MatchErrorCodeTimerPaused, MatchErrorCodeTeamPauseAlreadyUsed, MatchErrorCodeRobberyNotAvailable, MatchErrorCodeRobberyRequirementsNotMet, MatchErrorCodeAlignmentOverlap, MatchErrorCodeTbNotAvailable, MatchErrorCodeSurrenderEvidenceInvalid:
		return true
	}
	return false
}

func (e MatchErrorCode) String() string {
	return string(e)
}

func (e *MatchErrorCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchErrorCode", str)
	}
	return nil
}

func (e MatchErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchErrorCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchErrorCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchEventType string

const (
	MatchEventTypeMatchStarted                MatchEventType = "MATCH_STARTED"
	MatchEventTypeBanPhaseStarted             MatchEventType = "BAN_PHASE_STARTED"
	MatchEventTypePoolSlotBanned              MatchEventType = "POOL_SLOT_BANNED"
	MatchEventTypeTurnAdvanced                MatchEventType = "TURN_ADVANCED"
	MatchEventTypePickPhaseStarted            MatchEventType = "PICK_PHASE_STARTED"
	MatchEventTypePiecePlaced                 MatchEventType = "PIECE_PLACED"
	MatchEventTypeShiroPlaced                 MatchEventType = "SHIRO_PLACED"
	MatchEventTypeResultConfirmationRequested MatchEventType = "RESULT_CONFIRMATION_REQUESTED"
	MatchEventTypeBeatmapResultConfirmed      MatchEventType = "BEATMAP_RESULT_CONFIRMED"
	MatchEventTypePieceWon                    MatchEventType = "PIECE_WON"
	MatchEventTypePiecesSacrificed            MatchEventType = "PIECES_SACRIFICED"
	MatchEventTypePieceRobbed                 MatchEventType = "PIECE_ROBBED"
	MatchEventTypeAdditionalTimeGranted       MatchEventType = "ADDITIONAL_TIME_GRANTED"
	MatchEventTypeTimerCalibrated             MatchEventType = "TIMER_CALIBRATED"
	MatchEventTypeTimerPaused                 MatchEventType = "TIMER_PAUSED"
	MatchEventTypeTimerResumed                MatchEventType = "TIMER_RESUMED"
	MatchEventTypeMatchSuspended              MatchEventType = "MATCH_SUSPENDED"
	MatchEventTypeMatchResumed                MatchEventType = "MATCH_RESUMED"
	MatchEventTypeActionSkipped               MatchEventType = "ACTION_SKIPPED"
	MatchEventTypeMatchAborted                MatchEventType = "MATCH_ABORTED"
	MatchEventTypeRefereeProxyActionRecorded  MatchEventType = "REFEREE_PROXY_ACTION_RECORDED"
	MatchEventTypeTbRequested                 MatchEventType = "TB_REQUESTED"
	MatchEventTypeTbRequestAccepted           MatchEventType = "TB_REQUEST_ACCEPTED"
	MatchEventTypeTbRequestRejected           MatchEventType = "TB_REQUEST_REJECTED"
	MatchEventTypeTbRequestExpired            MatchEventType = "TB_REQUEST_EXPIRED"
	MatchEventTypeTbForced                    MatchEventType = "TB_FORCED"
	MatchEventTypeTbPreparationStarted        MatchEventType = "TB_PREPARATION_STARTED"
	MatchEventTypeTbStarted                   MatchEventType = "TB_STARTED"
	MatchEventTypeTbResultConfirmed           MatchEventType = "TB_RESULT_CONFIRMED"
	MatchEventTypeSurrenderRecorded           MatchEventType = "SURRENDER_RECORDED"
	MatchEventTypeMatchFinished               MatchEventType = "MATCH_FINISHED"
	MatchEventTypeStalemateDetected           MatchEventType = "STALEMATE_DETECTED"
	MatchEventTypeAdjudicationRequired        MatchEventType = "ADJUDICATION_REQUIRED"
	MatchEventTypeTimerStarted                MatchEventType = "TIMER_STARTED"
	MatchEventTypeTimerStopped                MatchEventType = "TIMER_STOPPED"
)

var AllMatchEventType = []MatchEventType{
	MatchEventTypeMatchStarted,
	MatchEventTypeBanPhaseStarted,
	MatchEventTypePoolSlotBanned,
	MatchEventTypeTurnAdvanced,
	MatchEventTypePickPhaseStarted,
	MatchEventTypePiecePlaced,
	MatchEventTypeShiroPlaced,
	MatchEventTypeResultConfirmationRequested,
	MatchEventTypeBeatmapResultConfirmed,
	MatchEventTypePieceWon,
	MatchEventTypePiecesSacrificed,
	MatchEventTypePieceRobbed,
	MatchEventTypeAdditionalTimeGranted,
	MatchEventTypeTimerCalibrated,
	MatchEventTypeTimerPaused,
	MatchEventTypeTimerResumed,
	MatchEventTypeMatchSuspended,
	MatchEventTypeMatchResumed,
	MatchEventTypeActionSkipped,
	MatchEventTypeMatchAborted,
	MatchEventTypeRefereeProxyActionRecorded,
	MatchEventTypeTbRequested,
	MatchEventTypeTbRequestAccepted,
	MatchEventTypeTbRequestRejected,
	MatchEventTypeTbRequestExpired,
	MatchEventTypeTbForced,
	MatchEventTypeTbPreparationStarted,
	MatchEventTypeTbStarted,
	MatchEventTypeTbResultConfirmed,
	MatchEventTypeSurrenderRecorded,
	MatchEventTypeMatchFinished,
	MatchEventTypeStalemateDetected,
	MatchEventTypeAdjudicationRequired,
	MatchEventTypeTimerStarted,
	MatchEventTypeTimerStopped,
}

func (e MatchEventType) IsValid() bool {
	switch e {
	case MatchEventTypeMatchStarted, MatchEventTypeBanPhaseStarted, MatchEventTypePoolSlotBanned, MatchEventTypeTurnAdvanced, MatchEventTypePickPhaseStarted, MatchEventTypePiecePlaced, MatchEventTypeShiroPlaced, MatchEventTypeResultConfirmationRequested, MatchEventTypeBeatmapResultConfirmed, MatchEventTypePieceWon, MatchEventTypePiecesSacrificed, MatchEventTypePieceRobbed, MatchEventTypeAdditionalTimeGranted, MatchEventTypeTimerCalibrated, MatchEventTypeTimerPaused, MatchEventTypeTimerResumed, MatchEventTypeMatchSuspended, MatchEventTypeMatchResumed, MatchEventTypeActionSkipped, MatchEventTypeMatchAborted, MatchEventTypeRefereeProxyActionRecorded, MatchEventTypeTbRequested, MatchEventTypeTbRequestAccepted, MatchEventTypeTbRequestRejected, MatchEventTypeTbRequestExpired, MatchEventTypeTbForced, MatchEventTypeTbPreparationStarted, MatchEventTypeTbStarted, MatchEventTypeTbResultConfirmed, MatchEventTypeSurrenderRecorded, MatchEventTypeMatchFinished, MatchEventTypeStalemateDetected, MatchEventTypeAdjudicationRequired, MatchEventTypeTimerStarted, MatchEventTypeTimerStopped:
		return true
	}
	return false
}

func (e MatchEventType) String() string {
	return string(e)
}

func (e *MatchEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchEventType", str)
	}
	return nil
}

func (e MatchEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchLifecycle string

const (
	MatchLifecycleReady                MatchLifecycle = "READY"
	MatchLifecycleRunning              MatchLifecycle = "RUNNING"
	MatchLifecycleSuspended            MatchLifecycle = "SUSPENDED"
	MatchLifecycleAdjudicationRequired MatchLifecycle = "ADJUDICATION_REQUIRED"
	MatchLifecycleFinished             MatchLifecycle = "FINISHED"
	MatchLifecycleAborted              MatchLifecycle = "ABORTED"
)

var AllMatchLifecycle = []MatchLifecycle{
	MatchLifecycleReady,
	MatchLifecycleRunning,
	MatchLifecycleSuspended,
	MatchLifecycleAdjudicationRequired,
	MatchLifecycleFinished,
	MatchLifecycleAborted,
}

func (e MatchLifecycle) IsValid() bool {
	switch e {
	case MatchLifecycleReady, MatchLifecycleRunning, MatchLifecycleSuspended, MatchLifecycleAdjudicationRequired, MatchLifecycleFinished, MatchLifecycleAborted:
		return true
	}
	return false
}

func (e MatchLifecycle) String() string {
	return string(e)
}

func (e *MatchLifecycle) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchLifecycle(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchLifecycle", str)
	}
	return nil
}

func (e MatchLifecycle) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchLifecycle) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchLifecycle) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MatchResultReason string

const (
	MatchResultReasonFourAlignment     MatchResultReason = "FOUR_ALIGNMENT"
	MatchResultReasonTb                MatchResultReason = "TB"
	MatchResultReasonSurrender         MatchResultReason = "SURRENDER"
	MatchResultReasonStalemateWonCount MatchResultReason = "STALEMATE_WON_COUNT"
)

var AllMatchResultReason = []MatchResultReason{
	MatchResultReasonFourAlignment,
	MatchResultReasonTb,
	MatchResultReasonSurrender,
	MatchResultReasonStalemateWonCount,
}

func (e MatchResultReason) IsValid() bool {
	switch e {
	case MatchResultReasonFourAlignment, MatchResultReasonTb, MatchResultReasonSurrender, MatchResultReasonStalemateWonCount:
		return true
	}
	return false
}

func (e MatchResultReason) String() string {
	return string(e)
}

func (e *MatchResultReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchResultReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchResultReason", str)
	}
	return nil
}

func (e MatchResultReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MatchResultReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MatchResultReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PieceMod string

const (
	PieceModNm    PieceMod = "NM"
	PieceModHd    PieceMod = "HD"
	PieceModHr    PieceMod = "HR"
	PieceModDt    PieceMod = "DT"
	PieceModFm    PieceMod = "FM"
	PieceModShiro PieceMod = "SHIRO"
	PieceModTb    PieceMod = "TB"
)

var AllPieceMod = []PieceMod{
	PieceModNm,
	PieceModHd,
	PieceModHr,
	PieceModDt,
	PieceModFm,
	PieceModShiro,
	PieceModTb,
}

func (e PieceMod) IsValid() bool {
	switch e {
	case PieceModNm, PieceModHd, PieceModHr, PieceModDt, PieceModFm, PieceModShiro, PieceModTb:
		return true
	}
	return false
}

func (e PieceMod) String() string {
	return string(e)
}

func (e *PieceMod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PieceMod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PieceMod", str)
	}
	return nil
}

func (e PieceMod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PieceMod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PieceMod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PieceState string

const (
	PieceStateNormal PieceState = "NORMAL"
	PieceStateBanned PieceState = "BANNED"
	PieceStatePicked PieceState = "PICKED"
	PieceStateWon    PieceState = "WON"
	PieceStateDead   PieceState = "DEAD"
)

var AllPieceState = []PieceState{
	PieceStateNormal,
	PieceStateBanned,
	PieceStatePicked,
	PieceStateWon,
	PieceStateDead,
}

func (e PieceState) IsValid() bool {
	switch e {
	case PieceStateNormal, PieceStateBanned, PieceStatePicked, PieceStateWon, PieceStateDead:
		return true
	}
	return false
}

func (e PieceState) String() string {
	return string(e)
}

func (e *PieceState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PieceState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PieceState", str)
	}
	return nil
}

func (e PieceState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PieceState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PieceState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PoolSlotState string

const (
	PoolSlotStateAvailable PoolSlotState = "AVAILABLE"
	PoolSlotStateBanned    PoolSlotState = "BANNED"
	PoolSlotStateSelected  PoolSlotState = "SELECTED"
)

var AllPoolSlotState = []PoolSlotState{
	PoolSlotStateAvailable,
	PoolSlotStateBanned,
	PoolSlotStateSelected,
}

func (e PoolSlotState) IsValid() bool {
	switch e {
	case PoolSlotStateAvailable, PoolSlotStateBanned, PoolSlotStateSelected:
		return true
	}
	return false
}

func (e PoolSlotState) String() string {
	return string(e)
}

func (e *PoolSlotState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PoolSlotState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PoolSlotState", str)
	}
	return nil
}

func (e PoolSlotState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PoolSlotState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PoolSlotState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RoomType string

const (
	RoomTypePrivate RoomType = "PRIVATE"
	RoomTypeCasual  RoomType = "CASUAL"
	RoomTypeMatch   RoomType = "MATCH"
)

var AllRoomType = []RoomType{
	RoomTypePrivate,
	RoomTypeCasual,
	RoomTypeMatch,
}

func (e RoomType) IsValid() bool {
	switch e {
	case RoomTypePrivate, RoomTypeCasual, RoomTypeMatch:
		return true
	}
	return false
}

func (e RoomType) String() string {
	return string(e)
}

func (e *RoomType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoomType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoomType", str)
	}
	return nil
}

func (e RoomType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RoomType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RoomType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TBBasis string

const (
	TBBasisCaptainAgreement         TBBasis = "CAPTAIN_AGREEMENT"
	TBBasisForcedAfterRobberyChecks TBBasis = "FORCED_AFTER_ROBBERY_CHECKS"
)

var AllTBBasis = []TBBasis{
	TBBasisCaptainAgreement,
	TBBasisForcedAfterRobberyChecks,
}

func (e TBBasis) IsValid() bool {
	switch e {
	case TBBasisCaptainAgreement, TBBasisForcedAfterRobberyChecks:
		return true
	}
	return false
}

func (e TBBasis) String() string {
	return string(e)
}

func (e *TBBasis) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TBBasis(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TBBasis", str)
	}
	return nil
}

func (e TBBasis) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TBBasis) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TBBasis) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TeamSide string

const (
	TeamSideRed  TeamSide = "RED"
	TeamSideBlue TeamSide = "BLUE"
)

var AllTeamSide = []TeamSide{
	TeamSideRed,
	TeamSideBlue,
}

func (e TeamSide) IsValid() bool {
	switch e {
	case TeamSideRed, TeamSideBlue:
		return true
	}
	return false
}

func (e TeamSide) String() string {
	return string(e)
}

func (e *TeamSide) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamSide(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamSide", str)
	}
	return nil
}

func (e TeamSide) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TeamSide) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TeamSide) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRolePlayer     UserRole = "PLAYER"
	UserRoleStrategist UserRole = "STRATEGIST"
	UserRoleReferee    UserRole = "REFEREE"
	UserRoleStreamer   UserRole = "STREAMER"
	UserRoleAdmin      UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRolePlayer,
	UserRoleStrategist,
	UserRoleReferee,
	UserRoleStreamer,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRolePlayer, UserRoleStrategist, UserRoleReferee, UserRoleStreamer, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VerifyStatus string

const (
	VerifyStatusVerified   VerifyStatus = "VERIFIED"
	VerifyStatusPending    VerifyStatus = "PENDING"
	VerifyStatusUnverified VerifyStatus = "UNVERIFIED"
)

var AllVerifyStatus = []VerifyStatus{
	VerifyStatusVerified,
	VerifyStatusPending,
	VerifyStatusUnverified,
}

func (e VerifyStatus) IsValid() bool {
	switch e {
	case VerifyStatusVerified, VerifyStatusPending, VerifyStatusUnverified:
		return true
	}
	return false
}

func (e VerifyStatus) String() string {
	return string(e)
}

func (e *VerifyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerifyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerifyStatus", str)
	}
	return nil
}

func (e VerifyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerifyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerifyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
