package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"rctHubBackend/internal/domain"
	"rctHubBackend/internal/matchengine"
	"rctHubBackend/pkg/paginate"
	"strings"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Author is the resolver for the author field.
func (r *announcementResolver) Author(ctx context.Context, obj *Announcement) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, obj.AuthorID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Author is the resolver for the author field.
func (r *beatmapResolver) Author(ctx context.Context, obj *Beatmap) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, obj.AuthorID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Selector is the resolver for the selector field.
func (r *beatmapResolver) Selector(ctx context.Context, obj *Beatmap) (*User, error) {
	if obj.SelectorID == nil || *obj.SelectorID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, *obj.SelectorID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Credits is the resolver for the credits field.
func (r *beatmapResolver) Credits(ctx context.Context, obj *Beatmap) ([]*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	users := make([]*User, 0, len(obj.CreditUserIDs))
	for _, id := range obj.CreditUserIDs {
		if id <= 0 {
			continue
		}
		u, err := loader.Load(ctx, id)
		if err != nil {
			return nil, err
		}
		if u != nil {
			users = append(users, mapUser(u))
		}
	}
	return users, nil
}

// Result is the resolver for the result field.
func (r *matchResolver) Result(ctx context.Context, obj *Match) (*MatchResult, error) {
	matchID, err := bson.ObjectIDFromHex(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	result, err := r.svc.Matchs.GetResult(ctx, matchID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapMatchResult(result), nil
}

// Moves is the resolver for the moves field.
func (r *matchResolver) Moves(ctx context.Context, obj *Match, limit *int, offset *int) ([]*Move, error) {
	matchID, err := bson.ObjectIDFromHex(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	params := buildPageParams(limit, limit)
	if offset != nil && *offset > 0 {
		perPage := params.PerPage
		if perPage <= 0 {
			perPage = 50
		}
		params.Page = int64(*offset)/perPage + 1
		params.PerPage = perPage
	}
	if params.PerPage <= 0 || params.PerPage > 100 {
		params.PerPage = 50
	}

	result, err := r.svc.Moves.ListByMatch(ctx, matchID, params)
	if err != nil {
		return nil, err
	}

	moves := make([]*Move, len(result.Data))
	for i := range result.Data {
		moves[i] = mapMove(&result.Data[i])
	}
	return moves, nil
}

// RecentMove is the resolver for the recentMove field.
func (r *matchResolver) RecentMove(ctx context.Context, obj *Match) (*Move, error) {
	matchID, err := bson.ObjectIDFromHex(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	moves, err := r.svc.Moves.LatestByMatch(ctx, matchID, 1)
	if err != nil {
		return nil, err
	}
	if len(moves) == 0 {
		return nil, nil
	}
	return mapMove(&moves[0]), nil
}

// Room is the resolver for the room field.
func (r *matchResolver) Room(ctx context.Context, obj *Match) (*Room, error) {
	roomID, err := bson.ObjectIDFromHex(obj.RoomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room ID: %w", err)
	}

	room, err := r.svc.Rooms.GetRoom(ctx, roomID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// StrategistView is the resolver for the strategistView field.
func (r *matchResolver) StrategistView(ctx context.Context, obj *Match) (*StrategistView, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return nil, fmt.Errorf("AUTH_REQUIRED")
	}
	return computeStrategistView(obj, claims.OsuID), nil
}

// SpectatorView is the resolver for the spectatorView field.
func (r *matchResolver) SpectatorView(ctx context.Context, obj *Match) (*SpectatorView, error) {
	view := computeSpectatorView(obj)

	matchID, err := bson.ObjectIDFromHex(obj.ID)
	if err == nil {
		params := paginate.Params{Page: 1, PerPage: 5}
		params.Normalize()
		result, err := r.svc.Moves.ListByMatch(ctx, matchID, params)
		if err == nil && len(result.Data) > 0 {
			view.RecentMoves = make([]*Move, len(result.Data))
			for i := range result.Data {
				view.RecentMoves[i] = mapMove(&result.Data[i])
			}
		}
	}

	return view, nil
}

// OverlayView is the resolver for the overlayView field.
func (r *matchResolver) OverlayView(ctx context.Context, obj *Match) (*OverlayView, error) {
	return computeOverlayView(obj), nil
}

// RefereeView is the resolver for the refereeView field.
func (r *matchResolver) RefereeView(ctx context.Context, obj *Match) (*RefereeView, error) {
	return computeRefereeView(obj), nil
}

// Operator is the resolver for the operator field.
func (r *moveResolver) Operator(ctx context.Context, obj *Move) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, obj.OperatorID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// StartMatch is the resolver for the startMatch field.
func (r *mutationResolver) StartMatch(ctx context.Context, input CommandMeta) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, &input, matchengine.StartMatch{}), nil
}

// BanPoolSlot is the resolver for the banPoolSlot field.
func (r *mutationResolver) BanPoolSlot(ctx context.Context, input BanPoolSlotInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.BanPoolSlot{PoolSlotID: input.PoolSlotID}), nil
}

// RefereeBanPoolSlot is the resolver for the refereeBanPoolSlot field.
func (r *mutationResolver) RefereeBanPoolSlot(ctx context.Context, input RefereeBanPoolSlotInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeBanPoolSlot{ActingTeam: engineTeam(input.ActingTeam), PoolSlotID: input.PoolSlotID, Reason: input.Reason}), nil
}

// PlacePiece is the resolver for the placePiece field.
func (r *mutationResolver) PlacePiece(ctx context.Context, input PlacePieceInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.PlacePiece{PoolSlotID: input.PoolSlotID, PieceID: pieceID(input.Meta.CommandID), Cell: cell}), nil
}

// RefereePlacePiece is the resolver for the refereePlacePiece field.
func (r *mutationResolver) RefereePlacePiece(ctx context.Context, input RefereePlacePieceInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.RefereePlacePiece{ActingTeam: engineTeam(input.ActingTeam), PoolSlotID: input.PoolSlotID, PieceID: pieceID(input.Meta.CommandID), Cell: cell, Reason: input.Reason}), nil
}

// PlaceShiro is the resolver for the placeShiro field.
func (r *mutationResolver) PlaceShiro(ctx context.Context, input PlaceShiroInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.PlaceShiro{PieceID: pieceID(input.Meta.CommandID), Cell: cell}), nil
}

// RefereePlaceShiro is the resolver for the refereePlaceShiro field.
func (r *mutationResolver) RefereePlaceShiro(ctx context.Context, input RefereePlaceShiroInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.RefereePlaceShiro{ActingTeam: engineTeam(input.ActingTeam), PieceID: pieceID(input.Meta.CommandID), Cell: cell, Reason: input.Reason}), nil
}

// RobPiece is the resolver for the robPiece field.
func (r *mutationResolver) RobPiece(ctx context.Context, input RobPieceInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RobPiece{TargetPieceID: input.TargetPieceID, SacrificeSets: input.SacrificeSets}), nil
}

// RefereeRobPiece is the resolver for the refereeRobPiece field.
func (r *mutationResolver) RefereeRobPiece(ctx context.Context, input RefereeRobPieceInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRobPiece{ActingTeam: engineTeam(input.ActingTeam), TargetPieceID: input.TargetPieceID, SacrificeSets: input.SacrificeSets, Reason: input.Reason}), nil
}

// ConfirmBeatmapResult is the resolver for the confirmBeatmapResult field.
func (r *mutationResolver) ConfirmBeatmapResult(ctx context.Context, input ConfirmBeatmapResultInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ConfirmBeatmapResult{BoardPieceID: input.BoardPieceID, WinningTeam: engineTeam(input.WinningTeam)}), nil
}

// GrantAdditionalTime is the resolver for the grantAdditionalTime field.
func (r *mutationResolver) GrantAdditionalTime(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.GrantAdditionalTime{Reason: input.Reason}), nil
}

// CalibrateTimer is the resolver for the calibrateTimer field.
func (r *mutationResolver) CalibrateTimer(ctx context.Context, input CalibrateTimerInput) (*MatchCommandResult, error) {
	if input.RemainingMilliseconds < 0 {
		return invalidCommandInput(input.Meta, fmt.Errorf("remainingMilliseconds cannot be negative")), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.CalibrateTimer{Remaining: milliseconds(input.RemainingMilliseconds), Reason: input.Reason}), nil
}

// PauseTimer is the resolver for the pauseTimer field.
func (r *mutationResolver) PauseTimer(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.PauseTimer{Reason: input.Reason}), nil
}

// ResumeTimer is the resolver for the resumeTimer field.
func (r *mutationResolver) ResumeTimer(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ResumeTimer{Reason: input.Reason}), nil
}

// SuspendMatch is the resolver for the suspendMatch field.
func (r *mutationResolver) SuspendMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.SuspendMatch{Reason: input.Reason}), nil
}

// ResumeMatch is the resolver for the resumeMatch field.
func (r *mutationResolver) ResumeMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ResumeMatch{Reason: input.Reason}), nil
}

// SkipCurrentAction is the resolver for the skipCurrentAction field.
func (r *mutationResolver) SkipCurrentAction(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.SkipCurrentAction{Reason: input.Reason}), nil
}

// AbortMatch is the resolver for the abortMatch field.
func (r *mutationResolver) AbortMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.AbortMatch{Reason: input.Reason}), nil
}

// RequestTb is the resolver for the requestTb field.
func (r *mutationResolver) RequestTb(ctx context.Context, input RequestTbInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RequestTB{RequestID: input.RequestID, Basis: matchengine.TBBasisCaptainAgreement}), nil
}

// RefereeRequestTb is the resolver for the refereeRequestTb field.
func (r *mutationResolver) RefereeRequestTb(ctx context.Context, input RefereeRequestTbInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRequestTB{ActingTeam: engineTeam(input.ActingTeam), RequestID: input.RequestID, Basis: matchengine.TBBasisCaptainAgreement, Reason: input.Reason}), nil
}

// RespondTbRequest is the resolver for the respondTbRequest field.
func (r *mutationResolver) RespondTbRequest(ctx context.Context, input RespondTbRequestInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RespondTBRequest{RequestID: input.RequestID, Accept: input.Accept}), nil
}

// RefereeRespondTbRequest is the resolver for the refereeRespondTbRequest field.
func (r *mutationResolver) RefereeRespondTbRequest(ctx context.Context, input RefereeRespondTbRequestInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRespondTBRequest{ActingTeam: engineTeam(input.ActingTeam), RequestID: input.RequestID, Accept: input.Accept, Reason: input.Reason}), nil
}

// StartTb is the resolver for the startTb field.
func (r *mutationResolver) StartTb(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.StartTB{Reason: input.Reason}), nil
}

// ConfirmTbResult is the resolver for the confirmTbResult field.
func (r *mutationResolver) ConfirmTbResult(ctx context.Context, input ConfirmTbResultInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ConfirmTBResult{WinningTeam: engineTeam(input.WinningTeam)}), nil
}

// RecordSurrender is the resolver for the recordSurrender field.
func (r *mutationResolver) RecordSurrender(ctx context.Context, input RecordSurrenderInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RecordSurrender{SurrenderingTeam: engineTeam(input.SurrenderingTeam), ConfirmingPlayerIDs: int64IDs(input.ConfirmingPlayerIds), Reason: input.Reason}), nil
}

// Beatmap is the resolver for the beatmap field.
func (r *poolSlotResolver) Beatmap(ctx context.Context, obj *PoolSlot) (*Beatmap, error) {
	if obj.BeatmapID == nil || *obj.BeatmapID <= 0 {
		return nil, nil
	}

	loader := BeatmapLoaderFromCtx(ctx)
	if loader != nil {
		b, err := loader.Load(ctx, *obj.BeatmapID)
		if err != nil {
			return nil, err
		}
		return mapBeatmap(b), nil
	}

	b, err := r.svc.Beatmaps.GetByOsuID(ctx, int64(*obj.BeatmapID))
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapBeatmap(b), nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return nil, nil
	}

	objID, err := bson.ObjectIDFromHex(claims.UserID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID in token: %w", err)
	}

	user, err := r.svc.Users.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	return mapUser(user), nil
}

// Match is the resolver for the match field.
func (r *queryResolver) Match(ctx context.Context, id string) (*Match, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	m, err := r.svc.Matchs.GetMatch(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapMatch(m), nil
}

// MatchByCode is the resolver for the matchByCode field.
func (r *queryResolver) MatchByCode(ctx context.Context, code string) (*Match, error) {
	m, err := r.svc.Matchs.GetMatchByCode(ctx, code)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapMatch(m), nil
}

// Matches is the resolver for the matches field.
func (r *queryResolver) Matches(ctx context.Context, status *MatchStatus, page *int, perPage *int) (*MatchPage, error) {
	var domainStatus *domain.MatchStatus
	if status != nil {
		s := domain.MatchStatus(strings.ToLower(string(*status)))
		domainStatus = &s
	}

	params := buildPageParams(page, perPage)
	result, err := r.svc.Matchs.List(ctx, params, domainStatus)
	if err != nil {
		return nil, err
	}
	return mapMatchPage(result), nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*Room, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid room ID: %w", err)
	}

	room, err := r.svc.Rooms.GetRoom(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// RoomByCode is the resolver for the roomByCode field.
func (r *queryResolver) RoomByCode(ctx context.Context, code string) (*Room, error) {
	room, err := r.svc.Rooms.GetRoomByCode(ctx, code)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, typeArg *RoomType, page *int, perPage *int) (*RoomPage, error) {
	var domainType *domain.RoomType
	if typeArg != nil {
		t := domain.RoomType(strings.ToLower(string(*typeArg)))
		domainType = &t
	}

	params := buildPageParams(page, perPage)
	result, err := r.svc.Rooms.GetRooms(ctx, params, domainType)
	if err != nil {
		return nil, err
	}
	return mapRoomPage(result), nil
}

// Beatmap is the resolver for the beatmap field.
func (r *queryResolver) Beatmap(ctx context.Context, id string) (*Beatmap, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid beatmap ID: %w", err)
	}

	b, err := r.svc.Beatmaps.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapBeatmap(b), nil
}

// BeatmapByOsuID is the resolver for the beatmapByOsuId field.
func (r *queryResolver) BeatmapByOsuID(ctx context.Context, osuID int) (*Beatmap, error) {
	b, err := r.svc.Beatmaps.GetByOsuID(ctx, int64(osuID))
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapBeatmap(b), nil
}

// Beatmaps is the resolver for the beatmaps field.
func (r *queryResolver) Beatmaps(ctx context.Context, page *int, perPage *int) (*BeatmapPage, error) {
	params := buildPageParams(page, perPage)
	result, err := r.svc.Beatmaps.List(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapBeatmapPage(result), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	u, err := r.svc.Users.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, page *int, perPage *int) (*UserPage, error) {
	params := buildPageParams(page, perPage)
	result, err := r.svc.Users.List(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapUserPage(result), nil
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context, page *int, perPage *int) (*AnnouncementPage, error) {
	params := buildPageParams(page, perPage)
	result, err := r.svc.Announcements.ListVisible(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapAnnouncementPage(result), nil
}

// Announcement is the resolver for the announcement field.
func (r *queryResolver) Announcement(ctx context.Context, id string) (*Announcement, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid announcement ID: %w", err)
	}

	a, err := r.svc.Announcements.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapAnnouncement(a), nil
}

// Owner is the resolver for the owner field.
func (r *roomResolver) Owner(ctx context.Context, obj *Room) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, obj.OwnerID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Match is the resolver for the match field.
func (r *roomResolver) Match(ctx context.Context, obj *Room) (*Match, error) {
	if obj.MatchID == nil || *obj.MatchID == "" {
		return nil, nil
	}

	matchID, err := bson.ObjectIDFromHex(*obj.MatchID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	m, err := r.svc.Matchs.GetMatch(ctx, matchID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapMatch(m), nil
}

// RedStrategist is the resolver for the redStrategist field.
func (r *roomSettingsResolver) RedStrategist(ctx context.Context, obj *RoomSettings) (*User, error) {
	if obj.RedStrategistUserID == nil || *obj.RedStrategistUserID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int(*obj.RedStrategistUserID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// BlueStrategist is the resolver for the blueStrategist field.
func (r *roomSettingsResolver) BlueStrategist(ctx context.Context, obj *RoomSettings) (*User, error) {
	if obj.BlueStrategistUserID == nil || *obj.BlueStrategistUserID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int(*obj.BlueStrategistUserID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Streamer is the resolver for the streamer field.
func (r *roomSettingsResolver) Streamer(ctx context.Context, obj *RoomSettings) (*User, error) {
	if obj.StreamerUserID == nil || *obj.StreamerUserID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int(*obj.StreamerUserID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Leader is the resolver for the leader field.
func (r *teamResolver) Leader(ctx context.Context, obj *Team) (*User, error) {
	if obj.LeaderID == nil || *obj.LeaderID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, *obj.LeaderID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Strategist is the resolver for the strategist field.
func (r *teamResolver) Strategist(ctx context.Context, obj *Team) (*User, error) {
	if obj.StrategistID == nil || *obj.StrategistID <= 0 {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, *obj.StrategistID)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// PlayerUsers is the resolver for the playerUsers field.
func (r *teamResolver) PlayerUsers(ctx context.Context, obj *Team) ([]*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	users := make([]*User, 0, len(obj.Players))
	for _, id := range obj.Players {
		if id <= 0 {
			continue
		}
		u, err := loader.Load(ctx, id)
		if err != nil {
			return nil, err
		}
		if u != nil {
			users = append(users, mapUser(u))
		}
	}
	return users, nil
}

// Announcement returns AnnouncementResolver implementation.
func (r *Resolver) Announcement() AnnouncementResolver { return &announcementResolver{r} }

// Beatmap returns BeatmapResolver implementation.
func (r *Resolver) Beatmap() BeatmapResolver { return &beatmapResolver{r} }

// Match returns MatchResolver implementation.
func (r *Resolver) Match() MatchResolver { return &matchResolver{r} }

// Move returns MoveResolver implementation.
func (r *Resolver) Move() MoveResolver { return &moveResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PoolSlot returns PoolSlotResolver implementation.
func (r *Resolver) PoolSlot() PoolSlotResolver { return &poolSlotResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Room returns RoomResolver implementation.
func (r *Resolver) Room() RoomResolver { return &roomResolver{r} }

// RoomSettings returns RoomSettingsResolver implementation.
func (r *Resolver) RoomSettings() RoomSettingsResolver { return &roomSettingsResolver{r} }

// Team returns TeamResolver implementation.
func (r *Resolver) Team() TeamResolver { return &teamResolver{r} }

type (
	announcementResolver struct{ *Resolver }
	beatmapResolver      struct{ *Resolver }
	matchResolver        struct{ *Resolver }
	moveResolver         struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	poolSlotResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	roomResolver         struct{ *Resolver }
	roomSettingsResolver struct{ *Resolver }
	teamResolver         struct{ *Resolver }
)
