package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"rctHubBackend/internal/beatmapmetadata"
	"rctHubBackend/internal/domain"
	"rctHubBackend/internal/irc"
	"rctHubBackend/internal/matchengine"
	"rctHubBackend/internal/repository"
	"rctHubBackend/internal/service"
	"rctHubBackend/pkg/errs"
	"slices"
	"strconv"
	"strings"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Author is the resolver for the author field.
func (r *announcementResolver) Author(ctx context.Context, obj *Announcement) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	id, err := parsePositiveInt64ID(obj.AuthorID)
	if err != nil {
		return nil, err
	}
	u, err := loader.Load(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Author is the resolver for the author field.
func (r *beatmapResolver) Author(ctx context.Context, obj *Beatmap) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	id, err := parsePositiveInt64ID(obj.AuthorID)
	if err != nil {
		return nil, err
	}
	u, err := loader.Load(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Beatmap is the resolver for the beatmap field.
func (r *mappoolEntryResolver) Beatmap(ctx context.Context, obj *MappoolEntry) (*Beatmap, error) {
	if obj == nil || obj.BeatmapID == nil {
		// SHIRO 槽不关联谱面
		return nil, nil
	}
	loader := BeatmapLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("BeatmapLoader not found in context")
	}
	b, err := loader.Load(ctx, int64(*obj.BeatmapID))
	if err != nil {
		return nil, err
	}
	return mapBeatmap(b), nil
}

// Selector is the resolver for the selector field.
func (r *mappoolEntryResolver) Selector(ctx context.Context, obj *MappoolEntry) (*User, error) {
	if obj == nil || obj.SelectorID == nil {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int64(*obj.SelectorID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Room is the resolver for the room field.
func (r *matchResolver) Room(ctx context.Context, obj *Match) (*Room, error) {
	roomID, err := bson.ObjectIDFromHex(obj.RoomID)
	if err != nil {
		return nil, fmt.Errorf("invalid room ID: %w", err)
	}

	room, err := r.svc.Rooms.GetRoom(ctx, roomID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// StrategistView is the resolver for the strategistView field.
func (r *matchResolver) StrategistView(ctx context.Context, obj *Match) (*StrategistView, error) {
	room, user, err := r.privateMatchContext(ctx, obj.ID, obj.RoomID)
	if err != nil {
		return nil, err
	}
	redTeam, blueTeam, err := r.loadLinkedTeams(ctx, room)
	if err != nil {
		return nil, err
	}
	team, err := strategistViewerTeam(user, room, redTeam, blueTeam)
	if err != nil {
		return nil, err
	}
	return computeStrategistView(obj.State, team, time.Now().UTC()), nil
}

// CaptainView is the resolver for the captainView field.
func (r *matchResolver) CaptainView(ctx context.Context, obj *Match) (*CaptainView, error) {
	room, user, err := r.privateMatchContext(ctx, obj.ID, obj.RoomID)
	if err != nil {
		return nil, err
	}
	redTeam, blueTeam, err := r.loadLinkedTeams(ctx, room)
	if err != nil {
		return nil, err
	}
	team, err := captainViewerTeam(user, room, redTeam, blueTeam)
	if err != nil {
		return nil, err
	}
	return computeCaptainView(obj.State, team, time.Now().UTC()), nil
}

// SpectatorView is the resolver for the spectatorView field.
func (r *matchResolver) SpectatorView(ctx context.Context, obj *Match) (*SpectatorView, error) {
	return computeSpectatorView(obj.Snapshot), nil
}

// OverlayView is the resolver for the overlayView field.
func (r *matchResolver) OverlayView(ctx context.Context, obj *Match) (*OverlayView, error) {
	return computeOverlayView(obj.Snapshot), nil
}

// RefereeView is the resolver for the refereeView field.
func (r *matchResolver) RefereeView(ctx context.Context, obj *Match) (*RefereeView, error) {
	room, user, err := r.privateMatchContext(ctx, obj.ID, obj.RoomID)
	if err != nil {
		return nil, err
	}
	if err := authorizeRefereeViewer(user, room); err != nil {
		return nil, err
	}
	return computeRefereeView(obj.ID, obj.State, time.Now().UTC()), nil
}

// Beatmap is the resolver for the beatmap field.
func (r *matchPoolSlotMetadataResolver) Beatmap(ctx context.Context, obj *MatchPoolSlotMetadata) (*Beatmap, error) {
	if r.metadata != nil {
		return r.persistedBeatmapMetadata(ctx, obj.BeatmapID)
	}
	return r.beatmapByID(ctx, obj.BeatmapID)
}

// MetadataStatus is the resolver for the metadataStatus field.
func (r *matchPoolSlotMetadataResolver) MetadataStatus(ctx context.Context, obj *MatchPoolSlotMetadata) (BeatmapMetadataStatus, error) {
	if obj == nil || obj.BeatmapID == nil || *obj.BeatmapID == "" {
		return BeatmapMetadataStatusNotConfigured, nil
	}
	if r.metadata != nil {
		record, err := r.metadataRecord(ctx, obj)
		if err != nil || record == nil {
			return BeatmapMetadataStatusFailed, nil
		}
		return BeatmapMetadataStatus(record.Status), nil
	}
	beatmap, err := r.beatmapByID(ctx, obj.BeatmapID)
	if err != nil {
		return BeatmapMetadataStatusFailed, nil
	}
	if beatmap == nil {
		return BeatmapMetadataStatusPending, nil
	}
	return BeatmapMetadataStatusReady, nil
}

// MetadataAttempts is the resolver for the metadataAttempts field.
func (r *matchPoolSlotMetadataResolver) MetadataAttempts(ctx context.Context, obj *MatchPoolSlotMetadata) (int, error) {
	record, err := r.metadataRecord(ctx, obj)
	if err != nil || record == nil {
		return 0, err
	}
	return record.Attempts, nil
}

// MetadataNextRetryAt is the resolver for the metadataNextRetryAt field.
func (r *matchPoolSlotMetadataResolver) MetadataNextRetryAt(ctx context.Context, obj *MatchPoolSlotMetadata) (*time.Time, error) {
	record, err := r.metadataRecord(ctx, obj)
	if err != nil || record == nil || record.Status == beatmapmetadata.StatusReady {
		return nil, err
	}
	value := record.NextTryAt
	return &value, nil
}

// MetadataLastError is the resolver for the metadataLastError field.
func (r *matchPoolSlotMetadataResolver) MetadataLastError(ctx context.Context, obj *MatchPoolSlotMetadata) (*string, error) {
	record, err := r.metadataRecord(ctx, obj)
	if err != nil || record == nil || record.LastError == "" {
		return nil, err
	}
	value := record.LastError
	return &value, nil
}

// StartMatch is the resolver for the startMatch field.
func (r *mutationResolver) StartMatch(ctx context.Context, input CommandMeta) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, &input, matchengine.StartMatch{}), nil
}

// ConfirmIRCResult is the resolver for the confirmIRCResult field.
func (r *mutationResolver) ConfirmIRCResult(ctx context.Context, input ConfirmIRCResultInput) (*MatchCommandResult, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return invalidCommandInput(nil, fmt.Errorf("authentication required")), nil
	}
	if r.irc == nil {
		return invalidCommandInput(nil, fmt.Errorf("IRC observation service is unavailable")), nil
	}
	observation, err := r.irc.ByID(ctx, input.ObservationID)
	if err != nil || observation == nil || !ircResultMatches(observation.Command, input.WinningTeam, input.BoardPieceID) {
		return invalidCommandInput(nil, fmt.Errorf("observation is unavailable")), nil
	}
	if err := r.authorizeIRCObservation(ctx, input.MatchID, observation.Channel); err != nil {
		return invalidCommandInput(nil, err), nil
	}
	matchID, err := bson.ObjectIDFromHex(input.MatchID)
	if err != nil {
		return invalidCommandInput(nil, fmt.Errorf("matchId must be a valid ObjectID")), nil
	}
	winner := engineTeam(input.WinningTeam)
	claimed, err := r.irc.ClaimConfirmation(ctx, input.ObservationID, matchID, input.CommandID, input.BoardPieceID, winner, claims.OsuID)
	if err != nil || claimed == nil || !ircResultMatches(claimed.Command, input.WinningTeam, input.BoardPieceID) {
		return invalidCommandInput(nil, fmt.Errorf("observation is unavailable")), nil
	}
	result := r.executeCommand(ctx, &CommandMeta{MatchID: input.MatchID, ExpectedVersion: input.ExpectedVersion, CommandID: input.CommandID}, matchengine.ConfirmBeatmapResult{BoardPieceID: input.BoardPieceID, WinningTeam: winner})
	if !result.Success {
		_ = r.irc.ReleaseConfirmation(ctx, input.ObservationID, input.CommandID)
		return result, nil
	}
	// A committed result remains authoritative even if this final evidence write
	// temporarily fails. The confirmation reconciler finishes it from the
	// durable command receipt after this request or a process restart.
	_ = r.irc.FinalizeConfirmation(ctx, input.ObservationID, input.CommandID)
	return result, nil
}

// RejectIRCObservation is the resolver for the rejectIRCObservation field.
func (r *mutationResolver) RejectIRCObservation(ctx context.Context, matchID string, observationID string, reason string) (bool, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return false, fmt.Errorf("AUTH_REQUIRED: authentication required")
	}
	if strings.TrimSpace(reason) == "" || r.irc == nil {
		return false, fmt.Errorf("reason and IRC observation service are required")
	}
	observation, err := r.irc.ByID(ctx, observationID)
	if err != nil {
		return false, err
	}
	if err := r.authorizeIRCObservation(ctx, matchID, observation.Channel); err != nil {
		return false, err
	}
	if err := r.irc.Reject(ctx, observationID, reason, claims.OsuID); err != nil {
		return false, err
	}
	return true, nil
}

// RetryIRCJob is the resolver for the retryIRCJob field.
func (r *mutationResolver) RetryIRCJob(ctx context.Context, input RetryIRCJobInput) (bool, error) {
	if r.ircJobs == nil {
		return false, fmt.Errorf("IRC job service is unavailable")
	}
	room, err := r.authorizeIRCMatch(ctx, input.MatchID)
	if err != nil {
		return false, err
	}
	channel, err := irc.ChannelFromMPLink(*room.Settings.MPLink)
	if err != nil {
		return false, fmt.Errorf("match multiplayer link is invalid")
	}
	matchID, err := bson.ObjectIDFromHex(input.MatchID)
	if err != nil {
		return false, fmt.Errorf("invalid match ID")
	}
	if err := r.ircJobs.Retry(ctx, matchID, input.JobID, channel, time.Now().UTC()); err != nil {
		return false, err
	}
	return true, nil
}

// RetryMatchAutomation is the resolver for the retryMatchAutomation field.
func (r *mutationResolver) RetryMatchAutomation(ctx context.Context, input RetryMatchAutomationInput) (bool, error) {
	if r.automation == nil {
		return false, fmt.Errorf("match automation service is unavailable")
	}
	if _, err := r.authorizeRefereeMatch(ctx, input.MatchID); err != nil {
		return false, err
	}
	matchID, err := bson.ObjectIDFromHex(input.MatchID)
	if err != nil {
		return false, fmt.Errorf("invalid match ID")
	}
	if err := r.automation.RetryFailedEvent(ctx, matchID, input.EventID); err != nil {
		return false, err
	}
	return true, nil
}

// RetryBeatmapMetadata is the resolver for the retryBeatmapMetadata field.
func (r *mutationResolver) RetryBeatmapMetadata(ctx context.Context, input RetryBeatmapMetadataInput) (bool, error) {
	if r.metadata == nil {
		return false, fmt.Errorf("beatmap metadata service is unavailable")
	}
	match, err := r.authorizeRefereeMatch(ctx, input.MatchID)
	if err != nil {
		return false, err
	}
	beatmapID, err := parsePositiveInt64ID(input.BeatmapID)
	if err != nil {
		return false, err
	}
	linked := false
	for _, configuredID := range match.Pool {
		if configuredID != nil && *configuredID == beatmapID {
			linked = true
			break
		}
	}
	if !linked {
		return false, fmt.Errorf("beatmap is not configured in this match")
	}
	if err := r.metadata.Retry(ctx, beatmapID); err != nil {
		return false, err
	}
	return true, nil
}

// BanPoolSlot is the resolver for the banPoolSlot field.
func (r *mutationResolver) BanPoolSlot(ctx context.Context, input BanPoolSlotInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.BanPoolSlot{PoolSlotID: input.PoolSlotID}), nil
}

// RefereeBanPoolSlot is the resolver for the refereeBanPoolSlot field.
func (r *mutationResolver) RefereeBanPoolSlot(ctx context.Context, input RefereeBanPoolSlotInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeBanPoolSlot{ActingTeam: engineTeam(input.ActingTeam), PoolSlotID: input.PoolSlotID, Reason: input.Reason}), nil
}

// PlacePiece is the resolver for the placePiece field.
func (r *mutationResolver) PlacePiece(ctx context.Context, input PlacePieceInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.PlacePiece{PoolSlotID: input.PoolSlotID, PieceID: pieceID(input.Meta.CommandID), Cell: cell}), nil
}

// RefereePlacePiece is the resolver for the refereePlacePiece field.
func (r *mutationResolver) RefereePlacePiece(ctx context.Context, input RefereePlacePieceInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.RefereePlacePiece{ActingTeam: engineTeam(input.ActingTeam), PoolSlotID: input.PoolSlotID, PieceID: pieceID(input.Meta.CommandID), Cell: cell, Reason: input.Reason}), nil
}

// PlaceShiro is the resolver for the placeShiro field.
func (r *mutationResolver) PlaceShiro(ctx context.Context, input PlaceShiroInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.PlaceShiro{PieceID: pieceID(input.Meta.CommandID), Cell: cell}), nil
}

// RefereePlaceShiro is the resolver for the refereePlaceShiro field.
func (r *mutationResolver) RefereePlaceShiro(ctx context.Context, input RefereePlaceShiroInput) (*MatchCommandResult, error) {
	cell, err := engineCell(input.Position)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.RefereePlaceShiro{ActingTeam: engineTeam(input.ActingTeam), PieceID: pieceID(input.Meta.CommandID), Cell: cell, Reason: input.Reason}), nil
}

// RobPiece is the resolver for the robPiece field.
func (r *mutationResolver) RobPiece(ctx context.Context, input RobPieceInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RobPiece{TargetPieceID: input.TargetPieceID, SacrificeSets: input.SacrificeSets}), nil
}

// RefereeRobPiece is the resolver for the refereeRobPiece field.
func (r *mutationResolver) RefereeRobPiece(ctx context.Context, input RefereeRobPieceInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRobPiece{ActingTeam: engineTeam(input.ActingTeam), TargetPieceID: input.TargetPieceID, SacrificeSets: input.SacrificeSets, Reason: input.Reason}), nil
}

// ConfirmBeatmapResult is the resolver for the confirmBeatmapResult field.
func (r *mutationResolver) ConfirmBeatmapResult(ctx context.Context, input ConfirmBeatmapResultInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ConfirmBeatmapResult{BoardPieceID: input.BoardPieceID, WinningTeam: engineTeam(input.WinningTeam)}), nil
}

// GrantAdditionalTime is the resolver for the grantAdditionalTime field.
func (r *mutationResolver) GrantAdditionalTime(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.GrantAdditionalTime{Reason: input.Reason}), nil
}

// CalibrateTimer is the resolver for the calibrateTimer field.
func (r *mutationResolver) CalibrateTimer(ctx context.Context, input CalibrateTimerInput) (*MatchCommandResult, error) {
	if input.RemainingMilliseconds < 0 {
		return invalidCommandInput(input.Meta, fmt.Errorf("remainingMilliseconds cannot be negative")), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.CalibrateTimer{Remaining: milliseconds(input.RemainingMilliseconds), Reason: input.Reason}), nil
}

// PauseTimer is the resolver for the pauseTimer field.
func (r *mutationResolver) PauseTimer(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.PauseTimer{Reason: input.Reason}), nil
}

// ResumeTimer is the resolver for the resumeTimer field.
func (r *mutationResolver) ResumeTimer(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ResumeTimer{Reason: input.Reason}), nil
}

// SuspendMatch is the resolver for the suspendMatch field.
func (r *mutationResolver) SuspendMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.SuspendMatch{Reason: input.Reason}), nil
}

// ResumeMatch is the resolver for the resumeMatch field.
func (r *mutationResolver) ResumeMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ResumeMatch{Reason: input.Reason}), nil
}

// SkipCurrentAction is the resolver for the skipCurrentAction field.
func (r *mutationResolver) SkipCurrentAction(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.SkipCurrentAction{Reason: input.Reason}), nil
}

// AbortMatch is the resolver for the abortMatch field.
func (r *mutationResolver) AbortMatch(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.AbortMatch{Reason: input.Reason}), nil
}

// RequestTb is the resolver for the requestTb field.
func (r *mutationResolver) RequestTb(ctx context.Context, input RequestTbInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RequestTB{RequestID: input.RequestID, Basis: matchengine.TBBasisCaptainAgreement}), nil
}

// RefereeRequestTb is the resolver for the refereeRequestTb field.
func (r *mutationResolver) RefereeRequestTb(ctx context.Context, input RefereeRequestTbInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRequestTB{ActingTeam: engineTeam(input.ActingTeam), RequestID: input.RequestID, Basis: matchengine.TBBasisCaptainAgreement, Reason: input.Reason}), nil
}

// RespondTbRequest is the resolver for the respondTbRequest field.
func (r *mutationResolver) RespondTbRequest(ctx context.Context, input RespondTbRequestInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RespondTBRequest{RequestID: input.RequestID, Accept: input.Accept}), nil
}

// RefereeRespondTbRequest is the resolver for the refereeRespondTbRequest field.
func (r *mutationResolver) RefereeRespondTbRequest(ctx context.Context, input RefereeRespondTbRequestInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.RefereeRespondTBRequest{ActingTeam: engineTeam(input.ActingTeam), RequestID: input.RequestID, Accept: input.Accept, Reason: input.Reason}), nil
}

// StartTb is the resolver for the startTb field.
func (r *mutationResolver) StartTb(ctx context.Context, input ReasonCommandInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.StartTB{Reason: input.Reason}), nil
}

// ConfirmTbResult is the resolver for the confirmTbResult field.
func (r *mutationResolver) ConfirmTbResult(ctx context.Context, input ConfirmTbResultInput) (*MatchCommandResult, error) {
	return r.executeCommand(ctx, input.Meta, matchengine.ConfirmTBResult{WinningTeam: engineTeam(input.WinningTeam)}), nil
}

// RecordSurrender is the resolver for the recordSurrender field.
func (r *mutationResolver) RecordSurrender(ctx context.Context, input RecordSurrenderInput) (*MatchCommandResult, error) {
	playerIDs, err := int64IDs(input.ConfirmingPlayerIds)
	if err != nil {
		return invalidCommandInput(input.Meta, err), nil
	}
	return r.executeCommand(ctx, input.Meta, matchengine.RecordSurrender{SurrenderingTeam: engineTeam(input.SurrenderingTeam), ConfirmingPlayerIDs: playerIDs, Reason: input.Reason}), nil
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, input TeamInput) (*Team, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Teams == nil {
		return nil, fmt.Errorf("team service is unavailable")
	}
	t := &domain.Team{
		Name:         input.Name,
		Description:  input.Description,
		Seed:         input.Seed,
		LeaderID:     intPtrToInt64Ptr(input.LeaderID),
		StrategistID: intPtrToInt64Ptr(input.StrategistID),
		Players:      intSliceToInt64Slice(input.PlayerIDs),
	}
	if err := r.svc.Teams.Create(ctx, t); err != nil {
		return nil, err
	}
	return mapTeam(t), nil
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id string, input TeamInput) (*Team, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Teams == nil {
		return nil, fmt.Errorf("team service is unavailable")
	}
	teamID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid team ID: %w", err)
	}
	t, err := r.svc.Teams.Patch(ctx, teamID, teamInputToPatch(&input))
	if err != nil {
		return nil, err
	}
	return mapTeam(t), nil
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, id string) (bool, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return false, err
	}
	if r.svc == nil || r.svc.Teams == nil {
		return false, fmt.Errorf("team service is unavailable")
	}
	teamID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid team ID: %w", err)
	}
	if err := r.svc.Teams.Delete(ctx, teamID); err != nil {
		return false, err
	}
	return true, nil
}

// CreateMappool is the resolver for the createMappool field.
func (r *mutationResolver) CreateMappool(ctx context.Context, input MappoolInput) (*Mappool, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Mappools == nil {
		return nil, fmt.Errorf("mappool service is unavailable")
	}
	m := mappoolInputToDomain(&input)
	if err := r.svc.Mappools.Create(ctx, m); err != nil {
		return nil, err
	}
	return mapMappool(m), nil
}

// UpdateMappool is the resolver for the updateMappool field.
func (r *mutationResolver) UpdateMappool(ctx context.Context, id string, input MappoolInput) (*Mappool, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Mappools == nil {
		return nil, fmt.Errorf("mappool service is unavailable")
	}
	mappoolID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid mappool ID: %w", err)
	}
	converted := mappoolInputToDomain(&input)
	patch := &service.MappoolPatch{
		Name:        &input.Name,
		Description: input.Description,
		Entries:     &converted.Entries,
	}
	m, err := r.svc.Mappools.Patch(ctx, mappoolID, patch)
	if err != nil {
		return nil, err
	}
	return mapMappool(m), nil
}

// DeleteMappool is the resolver for the deleteMappool field.
func (r *mutationResolver) DeleteMappool(ctx context.Context, id string) (bool, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return false, err
	}
	if r.svc == nil || r.svc.Mappools == nil {
		return false, fmt.Errorf("mappool service is unavailable")
	}
	mappoolID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return false, fmt.Errorf("invalid mappool ID: %w", err)
	}
	if err := r.svc.Mappools.Delete(ctx, mappoolID); err != nil {
		return false, err
	}
	return true, nil
}

// Beatmap is the resolver for the beatmap field.
func (r *poolSlotResolver) Beatmap(ctx context.Context, obj *PoolSlot) (*Beatmap, error) {
	return r.beatmapByID(ctx, obj.BeatmapID)
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return nil, nil
	}
	if r.users == nil {
		return nil, fmt.Errorf("current user reader is unavailable")
	}
	user, err := r.users.GetByOsuID(ctx, claims.OsuID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) || errors.Is(err, errs.ErrNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	return mapUser(user), nil
}

// Match is the resolver for the match field.
func (r *queryResolver) Match(ctx context.Context, id string) (*Match, error) {
	if r.formal == nil {
		return nil, fmt.Errorf("formal match read service is unavailable")
	}
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	m, err := r.formal.ByID(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) || errors.Is(err, errs.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapFormalMatch(m), nil
}

// MatchByCode is the resolver for the matchByCode field.
func (r *queryResolver) MatchByCode(ctx context.Context, code string) (*Match, error) {
	if r.formal == nil {
		return nil, fmt.Errorf("formal match read service is unavailable")
	}
	m, err := r.formal.ByCode(ctx, code)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) || errors.Is(err, errs.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapFormalMatch(m), nil
}

// Matches is the resolver for the matches field.
func (r *queryResolver) Matches(ctx context.Context, page *int, perPage *int) (*MatchPage, error) {
	if r.formal == nil {
		return nil, fmt.Errorf("formal match read service is unavailable")
	}
	params := buildPageParams(page, perPage)
	result, err := r.formal.List(ctx, params)
	if err != nil {
		return nil, err
	}
	items := make([]*Match, 0, len(result.Data))
	for index := range result.Data {
		items = append(items, mapFormalMatch(&result.Data[index]))
	}
	return &MatchPage{Items: items, Page: int(result.Page), PerPage: int(result.PerPage), Total: int(result.Total), TotalPages: int(result.TotalPages)}, nil
}

// Room is the resolver for the room field.
func (r *queryResolver) Room(ctx context.Context, id string) (*Room, error) {
	if _, err := r.privateViewer(ctx); err != nil {
		return nil, err
	}
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid room ID: %w", err)
	}

	room, err := r.svc.Rooms.GetRoom(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// RoomByCode is the resolver for the roomByCode field.
func (r *queryResolver) RoomByCode(ctx context.Context, code string) (*Room, error) {
	if _, err := r.privateViewer(ctx); err != nil {
		return nil, err
	}
	room, err := r.svc.Rooms.GetRoomByCode(ctx, code)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapRoom(room), nil
}

// Rooms is the resolver for the rooms field.
func (r *queryResolver) Rooms(ctx context.Context, typeArg *RoomType, search *string, round *string, status *MatchLifecycle, relatedToMe *bool, page *int, perPage *int) (*RoomPage, error) {
	viewer, err := r.privateViewer(ctx)
	if err != nil {
		return nil, err
	}
	filter := repository.RoomListFilter{}
	if typeArg != nil {
		t := domain.RoomType(strings.ToLower(string(*typeArg)))
		filter.Type = &t
	}
	if search != nil {
		filter.Search = *search
	}
	if round != nil {
		filter.Round = *round
	}
	if status != nil {
		filter.Lifecycle = string(*status)
	}
	if relatedToMe != nil && *relatedToMe {
		filter.RelatedUserID = &viewer.OnlineID
	}

	params := buildPageParams(page, perPage)
	result, err := r.svc.Rooms.GetRooms(ctx, params, filter)
	if err != nil {
		return nil, err
	}
	return mapRoomPage(result), nil
}

// Beatmap is the resolver for the beatmap field.
func (r *queryResolver) Beatmap(ctx context.Context, id string) (*Beatmap, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid beatmap ID: %w", err)
	}

	b, err := r.svc.Beatmaps.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapBeatmap(b), nil
}

// BeatmapByOsuID is the resolver for the beatmapByOsuId field.
func (r *queryResolver) BeatmapByOsuID(ctx context.Context, osuID int) (*Beatmap, error) {
	if osuID <= 0 {
		return nil, fmt.Errorf("osuId must be a positive integer")
	}
	b, err := r.svc.Beatmaps.GetByOsuID(ctx, int64(osuID))
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapBeatmap(b), nil
}

// Beatmaps is the resolver for the beatmaps field.
func (r *queryResolver) Beatmaps(ctx context.Context, search *string, page *int, perPage *int) (*BeatmapPage, error) {
	params := buildPageParams(page, perPage)
	term := ""
	if search != nil {
		term = *search
	}
	result, err := r.svc.Beatmaps.List(ctx, params, term)
	if err != nil {
		return nil, err
	}
	return mapBeatmapPage(result), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	u, err := r.svc.Users.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, page *int, perPage *int) (*UserPage, error) {
	params := buildPageParams(page, perPage)
	term := ""
	if search != nil {
		term = *search
	}
	result, err := r.svc.Users.List(ctx, params, term)
	if err != nil {
		return nil, err
	}
	return mapUserPage(result), nil
}

// Announcements is the resolver for the announcements field.
func (r *queryResolver) Announcements(ctx context.Context, page *int, perPage *int) (*AnnouncementPage, error) {
	params := buildPageParams(page, perPage)
	user, meErr := r.Me(ctx)
	var isPrivileged = false

	if user != nil && meErr == nil {
		if slices.Contains(user.Roles, UserRoleAdmin) {
			isPrivileged = true
		}
	}

	// Show all announcements based on current user.
	if isPrivileged {
		result, err := r.svc.Announcements.ListAll(ctx, params)
		if err != nil {
			return nil, err
		}
		return mapAnnouncementPage(result), nil
	}

	result, err := r.svc.Announcements.ListVisible(ctx, params)
	if err != nil {
		return nil, err
	}
	return mapAnnouncementPage(result), nil
}

// Announcement is the resolver for the announcement field.
func (r *queryResolver) Announcement(ctx context.Context, id string) (*Announcement, error) {
	objID, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, fmt.Errorf("invalid announcement ID: %w", err)
	}

	a, err := r.svc.Announcements.Get(ctx, objID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapAnnouncement(a), nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, search *string, page *int, perPage *int) (*TeamPage, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Teams == nil {
		return nil, fmt.Errorf("team service is unavailable")
	}
	params := buildPageParams(page, perPage)
	term := ""
	if search != nil {
		term = *search
	}
	result, err := r.svc.Teams.List(ctx, params, term)
	if err != nil {
		return nil, err
	}
	return mapTeamPage(result), nil
}

// Mappools is the resolver for the mappools field.
func (r *queryResolver) Mappools(ctx context.Context, search *string, page *int, perPage *int) (*MappoolPage, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r.svc == nil || r.svc.Mappools == nil {
		return nil, fmt.Errorf("mappool service is unavailable")
	}
	params := buildPageParams(page, perPage)
	term := ""
	if search != nil {
		term = *search
	}
	result, err := r.svc.Mappools.List(ctx, params, term)
	if err != nil {
		return nil, err
	}
	return mapMappoolPage(result), nil
}

// UserByOsuID is the resolver for the userByOsuId field.
// Read-through upsert: a cache miss on all tiers fetches from the osu! API
// and creates the local user (default player + pending), matching the
// beatmapByOsuId contract used by the admin "add user" flow (D4).
func (r *queryResolver) UserByOsuID(ctx context.Context, osuID int) (*User, error) {
	if _, err := r.adminViewer(ctx); err != nil {
		return nil, err
	}
	if r == nil || r.fetcher == nil {
		return nil, fmt.Errorf("user fetcher is unavailable")
	}
	if osuID <= 0 {
		return nil, fmt.Errorf("INVALID_REQUEST: osuId must be positive")
	}
	user, err := r.fetcher.GetUser(ctx, int64(osuID))
	if err != nil {
		return nil, err
	}
	return mapUser(user), nil
}

// IrcObservations is the resolver for the ircObservations field.
func (r *queryResolver) IrcObservations(ctx context.Context, matchID string, channel string) ([]*IRCObservation, error) {
	claims, ok := ClaimsFromCtx(ctx)
	if !ok || claims == nil {
		return nil, fmt.Errorf("AUTH_REQUIRED: authentication required")
	}
	if err := r.authorizeIRCObservation(ctx, matchID, channel); err != nil {
		return nil, err
	}
	if r.irc == nil {
		return nil, fmt.Errorf("IRC observation service is unavailable")
	}
	items, err := r.irc.List(ctx, channel, 100)
	if err != nil {
		return nil, err
	}
	result := make([]*IRCObservation, len(items))
	for i, item := range items {
		result[i] = mapIRCObservation(item)
	}
	return result, nil
}

// IrcJobs is the resolver for the ircJobs field.
func (r *queryResolver) IrcJobs(ctx context.Context, matchID string) ([]*IRCJob, error) {
	if r.ircJobs == nil {
		return nil, fmt.Errorf("IRC job service is unavailable")
	}
	if _, err := r.authorizeIRCMatch(ctx, matchID); err != nil {
		return nil, err
	}
	parsed, err := bson.ObjectIDFromHex(matchID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID")
	}
	items, err := r.ircJobs.List(ctx, parsed, 100)
	if err != nil {
		return nil, err
	}
	result := make([]*IRCJob, len(items))
	for i, item := range items {
		result[i] = mapIRCJob(item)
	}
	return result, nil
}

// IrcConnectionStatus is the resolver for the ircConnectionStatus field.
func (r *queryResolver) IrcConnectionStatus(ctx context.Context, matchID string) (*IRCConnectionStatus, error) {
	if _, err := r.authorizeRefereeMatch(ctx, matchID); err != nil {
		return nil, err
	}
	if r.ircStatus == nil {
		return &IRCConnectionStatus{Configured: false, Connected: false, Degraded: false}, nil
	}
	status := r.ircStatus.Status()
	return &IRCConnectionStatus{Configured: status.Configured, Connected: status.Connected, Degraded: status.Configured && !status.Connected, LastError: optionalString(status.LastError)}, nil
}

// AuditLog is the resolver for the auditLog field.
func (r *refereeViewResolver) AuditLog(ctx context.Context, obj *RefereeView, limit *int) ([]*AuditEntry, error) {
	if r.audit == nil {
		return nil, fmt.Errorf("match audit reader is unavailable")
	}
	matchID, err := bson.ObjectIDFromHex(obj.MatchID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}
	requested := 50
	if limit != nil {
		requested = *limit
	}
	actions, err := r.audit.ListActions(ctx, matchID, requested)
	if err != nil {
		return nil, err
	}
	entries := make([]*AuditEntry, len(actions))
	for index, action := range actions {
		entries[index] = &AuditEntry{
			ActionID: action.ID.Hex(), MatchID: action.MatchID.Hex(),
			Sequence: strconv.FormatUint(action.ResultingVersion, 10),
			Actor: &MatchCommandActor{
				OsuID: strconv.FormatInt(action.Actor.OsuID, 10), Capability: MatchActorCapability(action.Actor.Capability),
				Team: gqlTeamPtrValue(action.Actor.Team), AdminOverride: action.Actor.AdminOverride,
				RefereeOverride: action.Actor.RefereeOverride,
			},
			CommandType: action.CommandType, PreviousVersion: strconv.FormatUint(action.PreviousVersion, 10),
			ResultingVersion: strconv.FormatUint(action.ResultingVersion, 10), Timestamp: action.CreatedAt,
			Reason: optionalString(action.Reason),
		}
	}
	return entries, nil
}

// AutomationIssues is the resolver for the automationIssues field.
func (r *refereeViewResolver) AutomationIssues(ctx context.Context, obj *RefereeView, limit *int) ([]*MatchAutomationIssue, error) {
	if r.automation == nil {
		return nil, fmt.Errorf("match automation service is unavailable")
	}
	matchID, err := bson.ObjectIDFromHex(obj.MatchID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}
	requested := 50
	if limit != nil {
		requested = *limit
	}
	events, err := r.automation.ListFailedEvents(ctx, matchID, int64(requested))
	if err != nil {
		return nil, err
	}
	issues := make([]*MatchAutomationIssue, len(events))
	for index, event := range events {
		issues[index] = &MatchAutomationIssue{
			EventID: event.EventID, Sequence: strconv.FormatUint(event.Sequence, 10),
			EventType: MatchEventType(event.Type), Attempts: event.Attempts,
			LastError: event.LastError, OccurredAt: event.OccurredAt,
		}
	}
	return issues, nil
}

// Owner is the resolver for the owner field.
func (r *roomResolver) Owner(ctx context.Context, obj *Room) (*User, error) {
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	id, err := parsePositiveInt64ID(obj.OwnerID)
	if err != nil {
		return nil, err
	}
	u, err := loader.Load(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Referee is the resolver for the referee field.
func (r *roomResolver) Referee(ctx context.Context, obj *Room) (*User, error) {
	if obj.RefereeUserID == nil {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	id, err := parsePositiveInt64ID(*obj.RefereeUserID)
	if err != nil {
		return nil, err
	}
	u, err := loader.Load(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Match is the resolver for the match field.
func (r *roomResolver) Match(ctx context.Context, obj *Room) (*Match, error) {
	if obj.MatchID == nil || *obj.MatchID == "" {
		return nil, nil
	}
	if r.formal == nil {
		return nil, fmt.Errorf("formal match read service is unavailable")
	}

	matchID, err := bson.ObjectIDFromHex(*obj.MatchID)
	if err != nil {
		return nil, fmt.Errorf("invalid match ID: %w", err)
	}

	m, err := r.formal.ByID(ctx, matchID)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) || errors.Is(err, errs.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapFormalMatch(m), nil
}

// Streamer is the resolver for the streamer field.
func (r *roomSettingsResolver) Streamer(ctx context.Context, obj *RoomSettings) (*User, error) {
	if obj.StreamerUserID == nil {
		return nil, nil
	}
	id, err := parsePositiveInt64ID(*obj.StreamerUserID)
	if err != nil {
		return nil, err
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// RedTeam is the resolver for the redTeam field.
func (r *roomSettingsResolver) RedTeam(ctx context.Context, obj *RoomSettings) (*Team, error) {
	if obj == nil || obj.RedTeamID == nil {
		return nil, nil
	}
	team, err := r.loadTeamByID(ctx, *obj.RedTeamID)
	if err != nil {
		return nil, err
	}
	return mapTeam(team), nil
}

// BlueTeam is the resolver for the blueTeam field.
func (r *roomSettingsResolver) BlueTeam(ctx context.Context, obj *RoomSettings) (*Team, error) {
	if obj == nil || obj.BlueTeamID == nil {
		return nil, nil
	}
	team, err := r.loadTeamByID(ctx, *obj.BlueTeamID)
	if err != nil {
		return nil, err
	}
	return mapTeam(team), nil
}

// Mappool is the resolver for the mappool field.
func (r *roomSettingsResolver) Mappool(ctx context.Context, obj *RoomSettings) (*Mappool, error) {
	if obj == nil || obj.MappoolID == nil {
		return nil, nil
	}
	if r.svc == nil || r.svc.Mappools == nil {
		return nil, nil
	}
	parsed, err := bson.ObjectIDFromHex(*obj.MappoolID)
	if err != nil {
		return nil, nil
	}
	pool, err := r.svc.Mappools.Get(ctx, parsed)
	if err != nil {
		if errors.Is(err, errs.ErrNotFound) || errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return mapMappool(pool), nil
}

// Leader is the resolver for the leader field.
func (r *teamResolver) Leader(ctx context.Context, obj *Team) (*User, error) {
	if obj == nil || obj.LeaderID == nil {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int64(*obj.LeaderID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Strategist is the resolver for the strategist field.
func (r *teamResolver) Strategist(ctx context.Context, obj *Team) (*User, error) {
	if obj == nil || obj.StrategistID == nil {
		return nil, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	u, err := loader.Load(ctx, int64(*obj.StrategistID))
	if err != nil {
		return nil, err
	}
	return mapUser(u), nil
}

// Players is the resolver for the players field.
func (r *teamResolver) Players(ctx context.Context, obj *Team) ([]*User, error) {
	if obj == nil {
		return []*User{}, nil
	}
	loader := UserLoaderFromCtx(ctx)
	if loader == nil {
		return nil, fmt.Errorf("UserLoader not found in context")
	}
	users := make([]*User, 0, len(obj.PlayerIDs))
	for _, id := range obj.PlayerIDs {
		u, err := loader.Load(ctx, int64(id))
		if err != nil {
			return nil, err
		}
		if u != nil {
			users = append(users, mapUser(u))
		}
	}
	return users, nil
}

// Announcement returns AnnouncementResolver implementation.
func (r *Resolver) Announcement() AnnouncementResolver { return &announcementResolver{r} }

// Beatmap returns BeatmapResolver implementation.
func (r *Resolver) Beatmap() BeatmapResolver { return &beatmapResolver{r} }

// MappoolEntry returns MappoolEntryResolver implementation.
func (r *Resolver) MappoolEntry() MappoolEntryResolver { return &mappoolEntryResolver{r} }

// Match returns MatchResolver implementation.
func (r *Resolver) Match() MatchResolver { return &matchResolver{r} }

// MatchPoolSlotMetadata returns MatchPoolSlotMetadataResolver implementation.
func (r *Resolver) MatchPoolSlotMetadata() MatchPoolSlotMetadataResolver {
	return &matchPoolSlotMetadataResolver{r}
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PoolSlot returns PoolSlotResolver implementation.
func (r *Resolver) PoolSlot() PoolSlotResolver { return &poolSlotResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RefereeView returns RefereeViewResolver implementation.
func (r *Resolver) RefereeView() RefereeViewResolver { return &refereeViewResolver{r} }

// Room returns RoomResolver implementation.
func (r *Resolver) Room() RoomResolver { return &roomResolver{r} }

// RoomSettings returns RoomSettingsResolver implementation.
func (r *Resolver) RoomSettings() RoomSettingsResolver { return &roomSettingsResolver{r} }

// Team returns TeamResolver implementation.
func (r *Resolver) Team() TeamResolver { return &teamResolver{r} }

type (
	announcementResolver          struct{ *Resolver }
	beatmapResolver               struct{ *Resolver }
	mappoolEntryResolver          struct{ *Resolver }
	matchResolver                 struct{ *Resolver }
	matchPoolSlotMetadataResolver struct{ *Resolver }
	mutationResolver              struct{ *Resolver }
	poolSlotResolver              struct{ *Resolver }
	queryResolver                 struct{ *Resolver }
	refereeViewResolver           struct{ *Resolver }
	roomResolver                  struct{ *Resolver }
	roomSettingsResolver          struct{ *Resolver }
	teamResolver                  struct{ *Resolver }
)
